/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface _AudioQueueAllocateBuffer (JSONKitDeserializing)
- (id)mutableObjectFromJSONDataWithParseOptions:(unsigned int)fp8 error:(id *)fp12;
- (id)mutableObjectFromJSONDataWithParseOptions:(unsigned int)fp8;
- (id)mutableObjectFromJSONData;
- (id)objectFromJSONDataWithParseOptions:(unsigned int)fp8 error:(id *)fp12;
- (id)objectFromJSONDataWithParseOptions:(unsigned int)fp8;
- (id)objectFromJSONData;
@end

