/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface _AudioQueueAllocateBuffer (GTMKeyValueObservingAdditions)
- (void)gtm_stopObservingAllKeyPaths;
- (void)gtm_removeObserver:(id)fp8 forKeyPath:(id)fp12 selector:(SEL)fp16;
- (void)gtm_addObserver:(id)fp8 forKeyPath:(id)fp12 selector:(SEL)fp16 userInfo:(id)fp20 options:(unsigned int)fp24;
@end

