/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface _AudioQueueAllocateBuffer (CRNSHTTPURLResponseConstructorAdditions)
+ (id)cr_responseWithURL:(id)fp8 statusCode:(int)fp12 headerFields:(id)fp16;
+ (id)cr_archiveWithURL:(id)fp8 statusCode:(int)fp12 headerFields:(id)fp16;
@end

