/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface _AudioQueueAllocateBuffer (GTMUIImageResizeAdditions)
- (id)gtm_imageByRotating:(int)fp8;
- (id)gtm_imageByResizingToSize:(struct CGSize)fp8 preserveAspectRatio:(BOOL)fp16 trimToFit:(BOOL)fp20;
@end

