/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface _AudioQueueAllocateBuffer (NimbusAttributedLabel)
- (void)setKern:(float)fp8;
- (void)setKern:(float)fp8 range:(struct _NSRange)fp12;
- (void)setStrokeColor:(id)fp8;
- (void)setStrokeColor:(id)fp8 range:(struct _NSRange)fp12;
- (void)setStrokeWidth:(float)fp8;
- (void)setStrokeWidth:(float)fp8 range:(struct _NSRange)fp12;
- (void)setUnderlineStyle:(int)fp8 modifier:(int)fp12;
- (void)setUnderlineStyle:(int)fp8 modifier:(int)fp12 range:(struct _NSRange)fp16;
- (void)setFont:(id)fp8;
- (void)setFont:(id)fp8 range:(struct _NSRange)fp12;
- (void)setTextColor:(id)fp8;
- (void)setTextColor:(id)fp8 range:(struct _NSRange)fp12;
- (void)setTextAlignment:(unsigned char)fp8 lineBreakMode:(unsigned char)fp12;
- (void)setTextAlignment:(unsigned char)fp8 lineBreakMode:(unsigned char)fp12 range:(struct _NSRange)fp16;
@end

