/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NativeContentController.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "SyncObserverModelBridge-Protocol.h"

@class UITextView, UIViewController;

@interface AboutSyncController : NativeContentController <MFMailComposeViewControllerDelegate, SyncObserverModelBridge>
{
    struct Profile *profile_;
    UIViewController *controller_;
    struct scoped_ptr<SyncObserverBridge> observer_;
    UITextView *debugDisplay_;
    struct ObjCPropertyReleaser propertyReleaser_NewTabPageController_;
}

- (void)setDebugDisplay:(id)fp8;
- (id)debugDisplay;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onStateChanged;
- (void)mailComposeController:(id)fp8 didFinishWithResult:(int)fp12 error:(id)fp16;
- (void)sendMail:(id)fp8;
- (void)reload;
- (id)textToDisplay;
- (id)initWithProfile:(struct Profile *)fp8 controller:(id)fp12;

@end

