/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NativeContentController.h"

@class UITextView;

@interface AboutAppEventsController : NativeContentController
{
    UITextView *eventsView_;
    struct ObjCPropertyReleaser propertyReleaser_AboutAppEventsController_;
}

- (void)setEventsView:(id)fp8;
- (id)eventsView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithAppEventProvider:(id)fp8;

@end

