/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "AppEventProvider-Protocol.h"

@interface AppEventRecorder : _AudioQueueAllocateBuffer <AppEventProvider>
{
    struct TimeTicks timeOrigin_;
    struct deque<ios::app_event::AppEvent, std::allocator<ios::app_event::AppEvent>> appEvents_;
    unsigned int maxNumberOfEvents_;
    struct scoped_nsobject<NSNotificationCenter> testNotificationCenter_;
}

+ (id)sharedInstance;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)notificationCenter;
- (void)stopRecording;
- (void)startRecording;
- (void)addEvent:(id)fp8;
- (struct deque<ios::app_event::AppEvent, std::allocator<ios::app_event::AppEvent>>)getAppEvents;
- (void)dealloc;
- (id)initWithMaxNumberOfEvents:(unsigned int)fp8;

@end

