/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "OmniboxTextFieldDelegate-Protocol.h"

@interface AutocompleteTextFieldDelegate : _AudioQueueAllocateBuffer <OmniboxTextFieldDelegate>
{
    struct OmniboxViewIOS *editView_;
    BOOL forwardingOnDidChange_;
    BOOL processingUserEvent_;
}

- (void)willPaste;
- (BOOL)onCopy;
- (BOOL)textFieldShouldClear:(id)fp8;
- (void)textFieldDidEndEditing:(id)fp8;
- (void)textFieldDidBeginEditing:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)textFieldDidChange:(id)fp8;
- (BOOL)textField:(id)fp8 shouldChangeCharactersInRange:(struct _NSRange)fp12 replacementString:(id)fp20;
- (id)initWithEditView:(struct OmniboxViewIOS *)fp8;

@end

