/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface BlockPopupsTableViewController : _AudioQueueAllocateBuffer
{
    struct Profile *profile_;
    struct ListValue exceptions_;
    struct scoped_nsobject<UISwitch> blockPopupsSwitch_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateEditButton;
- (void)blockPopupsChanged:(id)fp8;
- (void)populateExceptionsList;
- (BOOL)popupsCurrentlyBlocked;
- (void)tableView:(id)fp8 commitEditingStyle:(int)fp12 forRowAtIndexPath:(id)fp16;
- (void)setEditing:(BOOL)fp8 animated:(BOOL)fp12;
- (BOOL)tableView:(id)fp8 canEditRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidUnload;
- (id)initWithProfile:(struct Profile *)fp8;

@end

