/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol BookmarkEditViewControllerDelegate
- (void)cancelEditor:(id)fp8;
- (void)bookmarkEditor:(id)fp8 didFinish:(const struct BookmarkNode *)fp12 withTitle:(id)fp16 url:(struct GURL)fp20 folder:(const struct BookmarkNode *)fp100 shouldDelete:(BOOL)fp104;
@end

