/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol BookmarkFolderAddViewControllerDelegate
- (void)bookmarkFolderEditor:(id)fp8 folderName:(id)fp12 parentFolder:(const struct BookmarkNode *)fp16;
@end

