/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BookmarkPanelController.h"

@interface BookmarkPanelController (BridgeMethods)
- (void)currentNodeDidDisappear:(const struct BookmarkNode *)fp8;
- (void)modelDidLoad;
- (void)updateNode:(const struct BookmarkNode *)fp8;
- (void)modelUpdated;
- (const struct BookmarkNode *)currentNode;
@end

