/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BookmarkEditViewController.h"

@interface BookmarkEditViewController (BridgeMethods)
- (void)folderListNeedsUpdate;
- (void)folderDidMove:(const struct BookmarkNode *)fp8;
- (void)folderDidDisappear;
- (void)editingBookmarkDidMove:(const struct BookmarkNode *)fp8;
- (void)editingBookmarkDidUpdate;
- (void)editingBookmarkDidDisappear;
- (const struct BookmarkNode *)folder;
@end

