/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class UITextField;

@interface BookmarkTextFieldCell : _AudioQueueAllocateBuffer
{
    UITextField *textField_;
}

- (void)setTextField:(id)fp8;
- (id)textField;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12 fieldTitle:(id)fp16;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

