/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface BookmarkNavButton : _AudioQueueAllocateBuffer
{
    const struct BookmarkNode *node_;
    struct ObjCPropertyReleaser propertyReleaser_BookmarkNavButton_;
    struct scoped_nsobject<UIImageView> breadcrumbView_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setEnabled:(BOOL)fp8;
- (void)setBookmarkNode:(const struct BookmarkNode *)fp8 withTitle:(id)fp12;
- (void)setBookmarkNode:(const struct BookmarkNode *)fp8;
- (const struct BookmarkNode *)node;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)fp8;

@end

