/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSMutableDictionary;

@interface BreakpadController : _AudioQueueAllocateBuffer
{
    struct dispatch_queue_s *queue_;
    void *breakpadRef_;
    NSMutableDictionary *configuration_;
    BOOL enableUploads_;
    int uploadIntervalInSeconds_;
}

+ (id)sharedInstance;
- (void)sendStoredCrashReports;
- (void)reportWillBeSent;
- (int)sendDelay;
- (void)withBreakpadRef:(id)fp(null);
- (void)removeUploadParameterForKey:(id)fp8;
- (void)addUploadParameter:(id)fp8 forKey:(id)fp12;
- (void)setUploadInterval:(int)fp8;
- (void)setUploadingURL:(id)fp8;
- (void)updateConfiguration:(id)fp8;
- (void)setUploadingEnabled:(BOOL)fp8;
- (void)stop;
- (void)start:(BOOL)fp8;
- (void)dealloc;
- (id)initSingleton;
- (id)init;

@end

