/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface BrowserViewControllerDependencyFactory : _AudioQueueAllocateBuffer
{
    struct Profile *profile_;
}

- (id)newWebToolbarControllerWithPrerenderProvider:(id)fp8;
- (id)newTabStripControllerWithTabModel:(id)fp8 style:(int)fp12;
- (id)newPrerenderController;
- (id)initWithProfile:(struct Profile *)fp8;

@end

