/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface BundleImageCache : _AudioQueueAllocateBuffer
{
}

+ (void)clear;
+ (int)count;
+ (id)stretchImageNamed:(id)fp8;
+ (id)stretchImageNamed:(id)fp8 leftCapWidth:(int)fp12 topCapHeight:(int)fp16;
+ (id)imageNamed:(id)fp8;

@end

