/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "StackCardViewProvider-Protocol.h"
#import "TabModelObserver-Protocol.h"

@class TabModel;

@interface CardSet : _AudioQueueAllocateBuffer <StackCardViewProvider, TabModelObserver>
{
    TabModel *tabModel_;
    struct scoped_nsobject<UIView> view_;
    struct scoped_nsobject<CardStackLayoutManager> stackModel_;
    id <CardSetObserver> observer_;
    BOOL ignoresTabModelChanges_;
    BOOL defersCardHiding_;
    BOOL keepOnlyVisibleCardViewsAlive_;
}

- (BOOL)keepOnlyVisibleCardViewsAlive;
- (BOOL)defersCardHiding;
- (BOOL)ignoresTabModelChanges;
- (void)setObserver:(id)fp8;
- (id)observer;
- (id)tabModel;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)isCardInEndStaggerRegion:(id)fp8;
- (BOOL)isCardInStartStaggerRegion:(id)fp8;
- (float)overextensionAmount;
- (BOOL)stackIsFullyOverextended;
- (BOOL)stackIsFullyFannedOut;
- (BOOL)stackIsFullyCollapsed;
- (BOOL)cardIsCollapsed:(id)fp8;
- (float)maximumStackLength;
- (void)tabModel:(id)fp8 replacedTab:(id)fp12 withTab:(id)fp16 atIndex:(unsigned int)fp20;
- (void)tabModel:(id)fp8 removedTab:(id)fp12 atIndex:(unsigned int)fp16;
- (void)tabModel:(id)fp8 insertedTab:(id)fp12 atIndex:(unsigned int)fp16 inForeground:(BOOL)fp20;
- (id)cardViewWithFrame:(struct CGRect)fp8 forStackCard:(id)fp24;
- (void)updateCardTabs;
- (void)updateCloseButtonExtensionsForCardView:(id)fp8;
- (void)displayCard:(id)fp8;
- (void)rebuildCards;
- (id)buildCardFromTab:(id)fp8;
- (void)clearGestureRecognizerTargetAndDelegateFromCards:(id)fp8;
- (BOOL)preloadNextCard;
- (void)updateCardVisibilities;
- (void)scrollCardAwayFromPrecedingNeighbor:(unsigned int)fp8;
- (void)eliminateOverextension;
- (BOOL)overextensionTowardStartOnCardAtIndex:(unsigned int)fp8;
- (BOOL)overextensionOnCardAtIndex:(unsigned int)fp8;
- (BOOL)stackIsOverextended;
- (void)scrollCardAtIndex:(unsigned int)fp8 byDelta:(float)fp12 allowEarlyOverscroll:(BOOL)fp16 decayOnOverscroll:(BOOL)fp20 scrollLeadingCards:(BOOL)fp24;
- (void)fanOutCardsWithStartIndex:(unsigned int)fp8;
- (void)fanOutCards;
- (void)layOutStartStack;
- (void)setLayoutAxisPosition:(float)fp8 isVertical:(BOOL)fp12;
- (void)setCardSize:(struct CGSize)fp8;
- (void)displayViewSizeWasChanged;
- (void)configureLayoutParametersWithMargin:(float)fp8;
- (void)setKeepOnlyVisibleCardViewsAlive:(BOOL)fp8;
- (void)setMaximumOverextensionAmount:(float)fp8;
- (float)maximumOverextensionAmount;
- (void)setDefersCardTabDisplayUpdating:(BOOL)fp8;
- (void)setDefersCardHiding:(BOOL)fp8;
- (void)setIgnoresTabModelChanges:(BOOL)fp8;
- (int)cardTabDisplaySide;
- (void)setDisplayView:(id)fp8;
- (id)displayView;
- (void)setCurrentCard:(id)fp8;
- (id)currentCard;
- (id)cards;
- (void)dealloc;
- (id)initWithModel:(id)fp8;
- (id)stackModel;

@end

