/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class TabModel;

@interface CardSideSwipeView : _AudioQueueAllocateBuffer
{
    int direction_;
    struct scoped_nsobject<CardView> leftCard_;
    struct scoped_nsobject<CardView> rightCard_;
    struct CGPoint currentPoint_;
    TabModel *model_;
    BOOL isEdge_;
    struct scoped_nsobject<UIImageView> backgroundView_;
    id <CardSideSwipeViewDelegate> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)finishPan;
- (void)handleHorizontalPan:(id)fp8;
- (void)updateCardPositions;
- (void)setupCard:(id)fp8 withIndex:(int)fp12;
- (void)updateCards;
- (void)updateViewsForDirection:(int)fp8;
- (void)setCardTabDisplaySide:(int)fp8;
- (id)initWithFrame:(struct CGRect)fp8 model:(id)fp24 isIncognito:(BOOL)fp28;

@end

