/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol CardSetObserver
- (void)cardSetRecreatedCards:(id)fp8;
- (void)cardSet:(id)fp8 displayedCard:(id)fp12;
- (void)cardSet:(id)fp8 removedCard:(id)fp12 atIndex:(unsigned int)fp16;
- (void)cardSet:(id)fp8 addedCard:(id)fp12;
@end

