/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface CardStackPinchGestureRecognizer : _AudioQueueAllocateBuffer
{
    unsigned int numberOfActiveTouches_;
}

- (unsigned int)numberOfActiveTouchesInEvent:(id)fp8;
- (void)reset;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (unsigned int)numberOfActiveTouches;

@end

