/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class UIButton, UIImage;

@interface CardTabView : _AudioQueueAllocateBuffer
{
    int displaySide_;
    UIImage *favicon_;
    struct scoped_nsobject<UIImage> tabImage_;
    UIButton *closeButton_;
    struct scoped_nsobject<UILabel> titleLabel_;
    BOOL isIncognito_;
    struct ObjCPropertyReleaser propertyReleaser_CardTabView_;
    float closeButtonHeightExtension_;
    float closeButtonWidthExtension_;
    BOOL defersUpdatingDisplay_;
}

- (BOOL)defersUpdatingDisplay;
- (float)closeButtonWidthExtension;
- (float)closeButtonHeightExtension;
- (id)favicon;
- (int)displaySide;
- (void)setCloseButton:(id)fp8;
- (id)closeButton;
- (id).cxx_construct;
- (void).cxx_destruct;
- (struct CGRect)closeButtonRect;
- (struct CGRect)faviconAndTitleRect;
- (struct CGRect)faviconRect;
- (struct CGRect)titleRect;
- (void)drawRect:(struct CGRect)fp8;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)setFavicon:(id)fp8;
- (void)setTitle:(id)fp8;
- (void)updateDisplay;
- (void)setDefersUpdatingDisplay:(BOOL)fp8;
- (void)setDisplaySide:(int)fp8;
- (void)updateCloseButtonPosition;
- (void)setCloseButtonWidthExtension:(float)fp8;
- (void)setCloseButtonHeightExtension:(float)fp8;
- (id)initWithFrame:(struct CGRect)fp8 isIncognito:(BOOL)fp24;
- (id)initWithFrame:(struct CGRect)fp8;

@end

