/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface CardView : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<UIImageView> contents_;
    struct scoped_nsobject<CardTabView> tab_;
    id cardCloseTarget_;
    SEL cardCloseAction_;
    BOOL isIncognito_;
    struct scoped_nsobject<UIImageView> frameLeft_;
    struct scoped_nsobject<UIImageView> frameRight_;
    struct scoped_nsobject<UIImageView> frameTop_;
    struct scoped_nsobject<UIImageView> frameBottom_;
    BOOL isActiveTab_;
}

- (void)setIsActiveTab:(BOOL)fp8;
- (BOOL)isActiveTab;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)pointInside:(struct CGPoint)fp8 withEvent:(id)fp16;
- (id)accessibilityValue;
- (void)setTabOpacity:(float)fp8;
- (void)setTabDisplaySide:(int)fp8;
- (void)layoutSubviews;
- (id)shadowPath;
- (struct CGRect)tabFrameForDisplaySide:(int)fp8;
- (void)updateImageBoundsAndZoom;
- (void)setCloseButtonExtensionWidth:(float)fp8 height:(float)fp12;
- (struct CGRect)closeButtonFrame;
- (void)addCardCloseTarget:(id)fp8 action:(SEL)fp12;
- (void)closeButtonWasTapped:(id)fp8;
- (void)setDefersUpdatingTabDisplay:(BOOL)fp8;
- (void)setFavicon:(id)fp8;
- (void)setTitle:(id)fp8;
- (id)image;
- (void)setImage:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8 isIncognito:(BOOL)fp24;
- (id)initWithFrame:(struct CGRect)fp8;

@end

