/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class ChromeToDevicePendingJobManager;

@interface ChromeToDeviceController : _AudioQueueAllocateBuffer
{
    id <ChromeToDeviceControllerDelegate> delegate_;
    struct ChromeToDeviceService *service_;
    struct ChromeToDeviceContentManagementService *contentManager_;
    struct scoped_ptr<ChromeToDeviceObserver> chromeToDeviceObserver_;
    ChromeToDevicePendingJobManager *pendingJobManager_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)notifyChromeToDeviceDownloadStateChange:(id)fp8 contentSaved:(BOOL)fp12;
- (void)onCancelAllPendingJobs;
- (void)onPrintToPhoneJobDownloadComplete:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp8 success:(_Bool)fp12 dataMimeType:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp16 dataString:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp20;
- (void)doOnPrintToPhoneJobSaveComplete:(BOOL)fp8 job:(id)fp12;
- (void)onPrintToPhoneJobDownloadStarts:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp8 title:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp12;
- (void)onSnapshotDataDownloadComplete:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp8 success:(_Bool)fp12 dataMimeType:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp16 dataString:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp20;
- (void)doOnSnapshotJobSaveComplete:(BOOL)fp8 job:(id)fp12;
- (void)onSnapshotUrlFetched:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp8 originalURL:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp12 title:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp16 isOfflineDataExpected:(_Bool)fp20 createTime:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp24;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8 profile:(struct Profile *)fp12;

@end

