/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface ChromeToDeviceErrorController : _AudioQueueAllocateBuffer
{
    struct Profile *profile_;
    struct scoped_nsobject<NSString> customMessage_;
    struct scoped_nsobject<UILabel> hintMessageLabel_;
    struct scoped_nsobject<UILabel> footerLabel_;
    BOOL needsViewUpdate_;
    struct scoped_nsobject<SettingsMultiLabelView> view_;
    struct scoped_ptr<ChromeToDeviceServiceStatusObserver> chromeToDeviceObserver_;
    id dataChangedTarget_;
    SEL dataChangedSelector_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setDataChangedTarget:(id)fp8 selector:(SEL)fp12;
- (void)onStateChanged;
- (void)initFooterLabel:(id)fp8 title:(id)fp12;
- (void)initErrorLabel:(id)fp8 title:(id)fp12;
- (void)addLabelWithTitle:(id)fp8;
- (float)heightForWidth:(float)fp8;
- (void)updateView;
- (void)initView;
- (BOOL)shouldUpdateView;
- (id)view;
- (void)setFooterMessage:(id)fp8;
- (void)setHintMessage:(id)fp8;
- (void)setCustomMessage:(id)fp8;
- (id)initWithProfile:(struct Profile *)fp8 dataChangedTarget:(id)fp12 selector:(SEL)fp16;
- (id)initWithProfile:(struct Profile *)fp8;

@end

