/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface ChromeWebViewFactory : _AudioQueueAllocateBuffer
{
}

+ (BOOL)isStaticFileUserAgent:(id)fp8;
+ (id)extractRawTabId:(id)fp8;
+ (id)newWebView:(struct CGRect)fp8;
+ (void)registerUserAgentInternal:(id)fp8;
+ (void)registerUserAgent:(id)fp8 useDesktopUserAgent:(BOOL)fp12;
+ (id)extractTabId:(id)fp8;
+ (BOOL)isStaticFileRequest:(id)fp8;
+ (id)newChromeStaticFileWebView:(struct CGRect)fp8 profile:(struct Profile *)fp24;
+ (id)newWebView:(struct CGRect)fp8 tabId:(id)fp24 useDesktopUserAgent:(BOOL)fp28;

@end

