/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSString, Tab;

@interface ChromeToDeviceJob : _AudioQueueAllocateBuffer
{
    NSString *jobId_;
    NSString *title_;
    NSString *fileName_;
    Tab *tab_;
    int status_;
    struct ObjCPropertyReleaser propertyReleaser_ChromeToDeviceJob_;
}

- (void)setStatus:(int)fp8;
- (int)status;
- (void)setTab:(id)fp8;
- (id)tab;
- (void)setFileName:(id)fp8;
- (id)fileName;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setJobId:(id)fp8;
- (id)jobId;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithId:(id)fp8 title:(id)fp12 fileName:(id)fp16 status:(int)fp20;

@end

