/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class ChromeToDevicePendingJobManager, Tab;

@interface ChromeToDeviceInfoBarHelper : _AudioQueueAllocateBuffer
{
    Tab *tab_;
    int infoBarType_;
    struct ChromeToDeviceInfoBarDelegate *infoBarDelegate_;
    struct scoped_nsobject<NSURL> dismissedInfoBarUrl_;
    int dismissedInfoBarType_;
    struct scoped_ptr<ChromeToDeviceInfoBarNotificationObserver> notification_observer_;
    struct scoped_ptr<ChromeToDeviceInfoBarDelegate::Delegate> viewOfflineContentBridge_;
    struct ChromeToDeviceContentManagementService *offlineContentService_;
    ChromeToDevicePendingJobManager *pendingJobManager_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)resetInfoBar:(struct InfoBarDelegate *)fp8;
- (BOOL)acceptViewOfflineCopyButtonPressed;
- (void)updateInfoBarSettings:(int)fp8;
- (int)computeInfoBarType;
- (void)refresh;
- (void)dealloc;
- (id)initWithOfflineContentService:(struct ChromeToDeviceContentManagementService *)fp8 tab:(id)fp12;

@end

