/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMUILocalizer.h"

@interface ChromeUILocalizer : GTMUILocalizer
{
}

- (id)localizedStringForString:(id)fp8;
- (void)awakeFromNib;

@end

