/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NativeContentController.h"

#import "SyncObserverModelBridge-Protocol.h"

@class UILabel;

@interface ChromeWelcomeController : NativeContentController <SyncObserverModelBridge>
{
    struct Profile *profile_;
    struct scoped_ptr<SyncObserverBridge> observer_;
    UILabel *syncEnabledLabel_;
    struct ObjCPropertyReleaser propertyReleaser_ChromeWelcomeController_;
}

- (void)setSyncEnabledLabel:(id)fp8;
- (id)syncEnabledLabel;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)takeATour:(id)fp8;
- (BOOL)isSyncEnabled;
- (void)onStateChanged;
- (void)reload;
- (id)initWithProfile:(struct Profile *)fp8;

@end

