/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NativeContentController.h"

@interface ChromeToDeviceContentController : NativeContentController
{
    struct Profile *profile_;
    _Bool hasStartedLoading_;
    struct scoped_nsobject<UIWebView> webView_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)handleLowMemory;
- (void)update:(id)fp8;
- (void)reload;
- (void)dealloc;
- (id)initWithProfile:(struct Profile *)fp8 url:(id)fp12;

@end

