/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface ChromeToDeviceRemoteNotificationRegistrar : _AudioQueueAllocateBuffer
{
    struct scoped_ptr<RemoteNotificationRegistrar> registrar_;
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)sharedInstance;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)isPushNotificationEnabled;
- (void)registerRemoteNotification:(struct ChromeToDeviceService *)fp8;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;

@end

