/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface ConfirmInfoBarController : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<InfoBarView> infoBarView_;
    struct InfoBarViewDelegate *delegate_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)infoBarButtonDidPress:(id)fp8;
- (void)infoBarDidCancel:(id)fp8;
- (void)layoutForDelegate:(struct ConfirmInfoBarDelegate *)fp8 frame:(struct CGRect)fp12;
- (void)onHeightsRecalculated:(int)fp8;
- (int)barHeight;
- (void)dealloc;
- (id)initWithDelegate:(struct InfoBarViewDelegate *)fp8;
- (id)view;

@end

