/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSMutableArray;

@interface ContextMenuHolder : _AudioQueueAllocateBuffer
{
    NSMutableArray *titles_;
    struct scoped_nsobject<NSMutableArray> actions_;
    struct ObjCPropertyReleaser propertyReleaser_ContextMenuHolder_;
}

- (void)setTitles:(id)fp8;
- (id)titles;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)performActionAtIndex:(unsigned int)fp8;
- (void)appendTitle:(id)fp8 action:(id)fp(null);
- (id)init;

@end

