/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "UIActionSheetDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@interface ContextMenuController : _AudioQueueAllocateBuffer <UIActionSheetDelegate, UIPopoverControllerDelegate>
{
    struct scoped_nsobject<ContextMenuHolder> menuHolder_;
    struct scoped_nsobject<UIActionSheet> sheet_;
    BOOL visible_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)showWithTitle:(id)fp8 holder:(id)fp12 atPoint:(struct CGPoint)fp16 inView:(id)fp24;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (BOOL)isVisible;
- (void)cleanup;

@end

