/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "TabModelObserver-Protocol.h"

@interface CrashReporterURLObserver : _AudioQueueAllocateBuffer <TabModelObserver>
{
    struct scoped_nsobject<NSMutableDictionary> breakpadKeyByTabId_;
    struct scoped_nsobject<NSMutableArray> breakpadKeys_;
}

+ (id)uniqueInstance;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)tabModel:(id)fp8 replacedTab:(id)fp12 withTab:(id)fp16 atIndex:(unsigned int)fp20;
- (void)tabModel:(id)fp8 removedTab:(id)fp12 atIndex:(unsigned int)fp16;
- (void)recordURL:(id)fp8 forTabId:(id)fp12;
- (void)removeTabId:(id)fp8;
- (void)urlChanged:(id)fp8;
- (id)init;

@end

