/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface CrashRestoreHelper : _AudioQueueAllocateBuffer
{
    struct Profile *profile_;
    BOOL needRestorantion_;
}

- (BOOL)restoreSessionsAfterCrash:(id)fp8;
- (void)moveAsideSessionInformation;
- (id)sessionBackupPath;
- (BOOL)deleteSessionForProfile:(struct Profile *)fp8 backupFile:(id)fp12;
- (void)showRestoreIfNeeded:(id)fp8;
- (id)initWithProfile:(struct Profile *)fp8;

@end

