/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface DelegateHolder : _AudioQueueAllocateBuffer
{
    struct UpgradeInfoBarDismissObserver observer_;
    struct UpgradeInfoBarDelegate *infoBarDelegate_;
}

- (struct UpgradeInfoBarDelegate *)infoBarDelegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithTabHelper:(struct InfoBarTabHelper *)fp8 tabId:(id)fp12 upgradeCenter:(id)fp16;

@end

