/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface DeterminateProgressBar : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<UIImageView> stretchableProgressView_;
    float progress_;
    BOOL isLoading_;
}

- (BOOL)isLoading;
- (float)progress;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)loadComplete;
- (void)hide;
- (void)show;
- (void)setProgress:(float)fp8;
- (void)layoutSubviews;
- (void)initializeInternal;
- (void)awakeFromNib;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

