/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "StaticHtmlNativeContent.h"

#import "HtmlGenerator-Protocol.h"

@interface ErrorPageContent : StaticHtmlNativeContent <HtmlGenerator>
{
    struct scoped_nsobject<NSString> html_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithLoader:(id)fp8 url:(id)fp12 error:(id)fp16;
- (void)generateHtml:(id)fp(null);
- (void)reload;

@end

