/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface EVCertAnimationView : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NSString> certName_;
    struct scoped_nsobject<UIFont> omniboxFont_;
    int textWidth_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)drawRect:(struct CGRect)fp8;
- (id)initWithEVName:(id)fp8 frame:(struct CGRect)fp12 textWidth:(int)fp28 omniboxFont:(id)fp32;

@end

