/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "UIAlertViewDelegate-Protocol.h"

@interface ExternalAppLauncher : _AudioQueueAllocateBuffer <UIAlertViewDelegate>
{
    struct scoped_nsobject<NSURL> telURL_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (BOOL)openURL:(id)fp8;
- (id)formatTelephoneNumber:(id)fp8;

@end

