/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface FancyTextField : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<UIImage> backgroundNormal_;
    struct scoped_nsobject<UIImage> backgroundFocused_;
    struct scoped_nsobject<UIImage> backgroundError_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setAppearanceToEditing:(BOOL)fp8;
- (void)initializeStyling;
- (void)setAppearanceToError;
- (BOOL)resignFirstResponder;
- (BOOL)becomeFirstResponder;
- (struct CGRect)editingRectForBounds:(struct CGRect)fp8;
- (struct CGRect)textRectForBounds:(struct CGRect)fp8;
- (struct CGRect)placeholderRectForBounds:(struct CGRect)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

