/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "UITextViewDelegate-Protocol.h"

@class NSString, NSURL, UIImage, UIImageView, UILabel, UISwitch, UITableViewCell, UITextField, UITextView, UIView;

@interface FeedbackTableViewController : _AudioQueueAllocateBuffer <UITextViewDelegate>
{
    UIView *headerView_;
    UIImageView *iconImageView_;
    UITableViewCell *feedbackTextCell_;
    UITableViewCell *screenshotCell_;
    UIView *screenshotBackground_;
    UIImageView *screenshotPreview_;
    UITableViewCell *systemDataCell_;
    UITableViewCell *urlCell_;
    UITableViewCell *accountCell_;
    UITextView *feedbackTextView_;
    UILabel *currentURLLabel_;
    UITextField *accountTextField_;
    NSString *account_;
    NSURL *currentURL_;
    UIImage *screenshot_;
    UISwitch *systemDataSwitch_;
    UISwitch *currentURLSwitch_;
    UISwitch *screenshotSwitch_;
    struct scoped_nsobject<UIBarButtonItem> sendFeedbackButton_;
    struct scoped_nsobject<UIBarButtonItem> cancelButton_;
    id <UserFeedbackActionDelegate> actionDelegate_;
    struct ObjCPropertyReleaser propertyReleaser_FeedbackTableViewController_;
}

- (void)setActionDelegate:(id)fp8;
- (id)actionDelegate;
- (void)setAccount:(id)fp8;
- (id)account;
- (void)setScreenshotSwitch:(id)fp8;
- (id)screenshotSwitch;
- (void)setCurrentURLSwitch:(id)fp8;
- (id)currentURLSwitch;
- (void)setSystemDataSwitch:(id)fp8;
- (id)systemDataSwitch;
- (void)setScreenshot:(id)fp8;
- (id)screenshot;
- (void)setCurrentURL:(id)fp8;
- (id)currentURL;
- (void)setCurrentURLLabel:(id)fp8;
- (id)currentURLLabel;
- (void)setFeedbackTextView:(id)fp8;
- (id)feedbackTextView;
- (void)setAccountTextField:(id)fp8;
- (id)accountTextField;
- (void)setAccountCell:(id)fp8;
- (id)accountCell;
- (void)setUrlCell:(id)fp8;
- (id)urlCell;
- (void)setSystemDataCell:(id)fp8;
- (id)systemDataCell;
- (void)setScreenshotPreview:(id)fp8;
- (id)screenshotPreview;
- (void)setScreenshotBackground:(id)fp8;
- (id)screenshotBackground;
- (void)setScreenshotCell:(id)fp8;
- (id)screenshotCell;
- (void)setFeedbackTextCell:(id)fp8;
- (id)feedbackTextCell;
- (void)setIconImageView:(id)fp8;
- (id)iconImageView;
- (void)setHeaderView:(id)fp8;
- (id)headerView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)feedbackData;
- (void)textViewDidBeginEditing:(id)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 titleForHeaderInSection:(int)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (BOOL)isRootViewController;
- (id)navigationItem;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)initWithDelegate:(id)fp8;

@end

