/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NSCoding-Protocol.h"

@class NSString, UIImage;

@interface FeedbackData : _AudioQueueAllocateBuffer <NSCoding>
{
    double timestamp_;
    NSString *appName_;
    NSString *appVersion_;
    NSString *executableName_;
    NSString *bundleIdentifier_;
    NSString *model_;
    NSString *platform_;
    NSString *iOSVersion_;
    NSString *account_;
    NSString *systemName_;
    int batteryState_;
    float batteryLevel_;
    NSString *feedbackText_;
    NSString *currentURL_;
    UIImage *screenshot_;
    NSString *filename_;
    struct ObjCPropertyReleaser propertyReleaser_FeedbackData_;
}

- (void)setFilename:(id)fp8;
- (id)filename;
- (void)setScreenshot:(id)fp8;
- (id)screenshot;
- (void)setCurrentURL:(id)fp8;
- (id)currentURL;
- (void)setFeedbackText:(id)fp8;
- (id)feedbackText;
- (void)setBatteryLevel:(float)fp8;
- (float)batteryLevel;
- (void)setBatteryState:(int)fp8;
- (int)batteryState;
- (void)setSystemName:(id)fp8;
- (id)systemName;
- (void)setAccount:(id)fp8;
- (id)account;
- (void)setIOSVersion:(id)fp8;
- (id)iOSVersion;
- (void)setPlatform:(id)fp8;
- (id)platform;
- (void)setModel:(id)fp8;
- (id)model;
- (void)setBundleIdentifier:(id)fp8;
- (id)bundleIdentifier;
- (void)setExecutableName:(id)fp8;
- (id)executableName;
- (void)setAppVersion:(id)fp8;
- (id)appVersion;
- (void)setAppName:(id)fp8;
- (id)appName;
- (void)setTimestamp:(double)fp8;
- (double)timestamp;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)stringForBatteryState:(int)fp8;
- (id)description;
- (id)stringValue;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)init;

@end

