/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "UITextFieldDelegate-Protocol.h"

@class FindBarTextField, UIButton, UILabel, UIView;

@interface FindBarControllerIOS : _AudioQueueAllocateBuffer <UITextFieldDelegate>
{
    UIView *view_;
    FindBarTextField *inputField_;
    UILabel *inputOverlay_;
    UIButton *nextButton_;
    UIButton *previousButton_;
    UIButton *closeButton_;
    BOOL isIncognito_;
    struct scoped_nsobject<NSTimer> delayTimer_;
    struct ObjCPropertyReleaser propertyReleaser_FindInPageController_;
}

- (void)setCloseButton:(id)fp8;
- (id)closeButton;
- (void)setPreviousButton:(id)fp8;
- (id)previousButton;
- (void)setNextButton:(id)fp8;
- (id)nextButton;
- (void)setInputOverlay:(id)fp8;
- (id)inputOverlay;
- (void)setInputField:(id)fp8;
- (id)inputField;
- (id)view;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)editingChanged:(id)fp8;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (void)textChanged;
- (id)imageWithName:(id)fp8;
- (void)hideKeyboard:(id)fp8;
- (void)hideFindBarView:(BOOL)fp8;
- (void)addFindBarView:(BOOL)fp8 intoView:(id)fp12 withFrame:(struct CGRect)fp16;
- (void)showIPhoneFindBarView:(BOOL)fp8 intoView:(id)fp12 withFrame:(struct CGRect)fp16;
- (void)showIPadFindBarView:(BOOL)fp8 intoView:(id)fp12 withFrame:(struct CGRect)fp16;
- (void)updateView:(id)fp8 initialUpdate:(BOOL)fp12;
- (id)searchTerm;
- (void)setUpIPad;
- (void)setUpIPhone;
- (id)initWithIncognito:(BOOL)fp8;

@end

