/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "FirstRunIpadViewControllerProtocol-Protocol.h"
#import "SyncLoginViewControllerProtocol-Protocol.h"

@class FancyTextField, PrimaryActionButton, SecondaryActionButton, UILabel, UIView;

@interface FirstRunLoginViewController : _AudioQueueAllocateBuffer <FirstRunIpadViewControllerProtocol, SyncLoginViewControllerProtocol>
{
    UIView *contentView_;
    UIView *titleView_;
    UIView *shadowedView_;
    UIView *aboutView_;
    UIView *signInView_;
    FancyTextField *loginField_;
    FancyTextField *passwordField_;
    UILabel *errorMessage_;
    PrimaryActionButton *signInButton_;
    SecondaryActionButton *skipButton_;
    UIView *activityIndicator_;
    struct scoped_nsobject<FirstRunIpadAdjuster> ipadAdjuster_;
    id <FirstRunMetricsDelegate> metrics_;
    struct ChromeLoginControllerDelegate *loginDelegate_;
    struct ObjCPropertyReleaser propertyReleaser_FirstRunLoginViewController_;
}

- (void)setSkipButton:(id)fp8;
- (id)skipButton;
- (void)setSignInButton:(id)fp8;
- (id)signInButton;
- (void)setErrorMessage:(id)fp8;
- (id)errorMessage;
- (void)setPasswordField:(id)fp8;
- (id)passwordField;
- (void)setLoginField:(id)fp8;
- (id)loginField;
- (void)setSignInView:(id)fp8;
- (id)signInView;
- (void)setAboutView:(id)fp8;
- (id)aboutView;
- (void)setTitleView:(id)fp8;
- (id)titleView;
- (void)setContentView:(id)fp8;
- (id)contentView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)credentialsEntered;
- (void)textFieldChanged:(id)fp8;
- (void)adjustIphoneViewForKeyboard;
- (void)updateControlStateForLoggingIn:(BOOL)fp8;
- (void)cancelPressed:(id)fp8;
- (void)credentialsOkPressed:(id)fp8;
- (void)nextTextField:(id)fp8;
- (void)setLoggingOutWithUserName:(id)fp8;
- (void)setLoggingInWithUserName:(id)fp8 errorState:(int)fp12 allowUserNameChange:(BOOL)fp16;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)stopAdjustForKeyboard;
- (void)startAdjustForKeyboard;
- (void)dealloc;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)initWithLoginDelegate:(struct ChromeLoginControllerDelegate *)fp8 metrics:(id)fp12;

@end

