/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "FirstRunIpadViewControllerProtocol-Protocol.h"
#import "SyncCaptchaViewControllerProtocol-Protocol.h"

@class FancyTextField, PrimaryActionButton, SecondaryActionButton, UIImageView, UIView;

@interface FirstRunCaptchaViewController : _AudioQueueAllocateBuffer <FirstRunIpadViewControllerProtocol, SyncCaptchaViewControllerProtocol>
{
    UIView *contentView_;
    UIView *shadowedView_;
    UIView *titleView_;
    UIImageView *captchaImageView_;
    FancyTextField *captchaEntry_;
    PrimaryActionButton *signInButton_;
    SecondaryActionButton *skipButton_;
    UIView *activityIndicator_;
    struct ChromeLoginControllerDelegate *loginDelegate_;
    struct scoped_nsobject<FirstRunIpadAdjuster> ipadAdjuster_;
    struct ObjCPropertyReleaser propertyReleaser_FirstRunCaptchaViewController_;
}

- (void)setSkipButton:(id)fp8;
- (id)skipButton;
- (void)setSignInButton:(id)fp8;
- (id)signInButton;
- (void)setCaptchaEntry:(id)fp8;
- (id)captchaEntry;
- (void)setCaptchaImageView:(id)fp8;
- (id)captchaImageView;
- (void)setTitleView:(id)fp8;
- (id)titleView;
- (void)setContentView:(id)fp8;
- (id)contentView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setCaptchaImage:(id)fp8;
- (void)cancelPressed:(id)fp8;
- (void)signInPressed:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillDisappear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)initWithLoginDelegate:(struct ChromeLoginControllerDelegate *)fp8;

@end

