/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface GestureStateTracker : _AudioQueueAllocateBuffer
{
    unsigned int scrollCardIndex_;
    float previousScrollOffset_;
    struct TimeTicks previousScrollTime_;
    float scrollVelocity_;
    BOOL resetScrollCardOnNextDrag_;
    unsigned int firstPinchCardIndex_;
    unsigned int secondPinchCardIndex_;
    float previousFirstPinchOffset_;
    float previousSecondPinchOffset_;
    BOOL pinching_;
    BOOL scrollingInPinch_;
    float swipeStartingPosition_;
    BOOL swipeChangesDecks_;
    unsigned int swipedCardIndex_;
    BOOL resetSwipedCardOnNextSwipe_;
    BOOL swipeIsBeginning_;
    BOOL ambiguousSwipeChangesDecks_;
}

- (void)setAmbiguousSwipeChangesDecks:(BOOL)fp8;
- (BOOL)ambiguousSwipeChangesDecks;
- (void)setSwipeIsBeginning:(BOOL)fp8;
- (BOOL)swipeIsBeginning;
- (void)setResetSwipedCardOnNextSwipe:(BOOL)fp8;
- (BOOL)resetSwipedCardOnNextSwipe;
- (void)setSwipedCardIndex:(unsigned int)fp8;
- (unsigned int)swipedCardIndex;
- (void)setSwipeChangesDecks:(BOOL)fp8;
- (BOOL)swipeChangesDecks;
- (void)setSwipeStartingPosition:(float)fp8;
- (float)swipeStartingPosition;
- (void)setScrollingInPinch:(BOOL)fp8;
- (BOOL)scrollingInPinch;
- (void)setPinching:(BOOL)fp8;
- (BOOL)pinching;
- (void)setPreviousSecondPinchOffset:(float)fp8;
- (float)previousSecondPinchOffset;
- (void)setPreviousFirstPinchOffset:(float)fp8;
- (float)previousFirstPinchOffset;
- (void)setSecondPinchCardIndex:(unsigned int)fp8;
- (unsigned int)secondPinchCardIndex;
- (void)setFirstPinchCardIndex:(unsigned int)fp8;
- (unsigned int)firstPinchCardIndex;
- (void)setResetScrollCardOnNextDrag:(BOOL)fp8;
- (BOOL)resetScrollCardOnNextDrag;
- (float)scrollVelocity;
- (void)setPreviousScrollTime:(struct TimeTicks)fp8;
- (struct TimeTicks)previousScrollTime;
- (void)setPreviousScrollOffset:(float)fp8;
- (float)previousScrollOffset;
- (void)setScrollCardIndex:(unsigned int)fp8;
- (unsigned int)scrollCardIndex;
- (id).cxx_construct;
- (void)updateScrollVelocityWithScrollDistance:(float)fp8;
- (id)init;

@end

