/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GIPGoogleDialogDelegate <NSObject>
- (void)dialog:(id)fp8 defaultButtonDidPress:(id)fp12;
- (void)dialog:(id)fp8 rightButtonDidPress:(id)fp12;
- (void)dialog:(id)fp8 leftButtonDidPress:(id)fp12;
@end

