/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class GIPGoogleDialogView, GIPResourceLoader, UIView, UIWindow;

@interface GIPGoogleDialogController : _AudioQueueAllocateBuffer
{
    UIWindow *window_;
    UIView *dimmingView_;
    GIPGoogleDialogView *dialogView_;
    int dialogBorderState_;
    id <GIPGoogleDialogDelegate> delegate_;
    BOOL contentViewShouldFillDialog_;
    GIPResourceLoader *imageLoader_;
    int orientation_;
}

- (int)orientation;
- (BOOL)contentViewShouldFillDialog;
- (id)dialogView;
- (void)setDialogBorderState:(int)fp8;
- (int)dialogBorderState;
- (void)interfaceDidRotate:(id)fp8;
- (void)setContentViewShouldFillDialog:(BOOL)fp8;
- (id)contentView;
- (struct CGRect)dialogViewFrame;
- (void)setDialogBorderState:(int)fp8 title:(id)fp12 caption:(id)fp16 lines:(int)fp20 icon:(id)fp24 buttonTitles:(id)fp28;
- (void)setDialogBorderState:(int)fp8 text:(id)fp12 lines:(int)fp16 icon:(id)fp20 buttonTitles:(id)fp24;
- (void)setTitle:(id)fp8 withFontSize:(float)fp12 numberOfLines:(int)fp16;
- (void)relayout;
- (void)defaultButtonDidPress:(id)fp8;
- (void)rightButtonDidPress:(id)fp8;
- (void)leftButtonDidPress:(id)fp8;
- (void)dialogDidPress:(id)fp8;
- (BOOL)isHidden;
- (void)setHidden:(BOOL)fp8;
- (void)windowDidBecomeVisible:(id)fp8;
- (id)window;
- (void)setBundleName:(id)fp8;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)loadWindow;
- (id)initWithDelegate:(id)fp8 loader:(id)fp12 fillContent:(BOOL)fp16;
- (id)initWithDelegate:(id)fp8 fillContent:(BOOL)fp12;
- (id)initWithDelegate:(id)fp8;

@end

