/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class UIImageView, UIView;

@interface GIPMicrophoneVolumeView : _AudioQueueAllocateBuffer
{
    UIView *micContainer_;
    UIImageView *micBackground_;
    UIImageView *micShadow_;
}

- (void)setVolumePercentage:(float)fp8;
- (id)maskLayer;
- (id)initWithResourceLoader:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

