/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GIPGoogleDialogController.h"

@class GIPResourceLoader, GIPSpeechFeedbackView, NSString, NSTimer, UIImage;

@interface GIPSpeechWindowController : GIPGoogleDialogController
{
    GIPSpeechFeedbackView *feedbackView_;
    NSTimer *inputLevelTimer_;
    float *inputLevelValues_;
    int inputLevelValueIndex_;
    GIPResourceLoader *speechResourceLoader_;
    id <GIPSpeechWindowDelegate> speechDelegate_;
    UIImage *micImage_;
    UIImage *cautionImage_;
    int feedbackViewState_;
    NSString *languageName_;
}

- (void)setLanguageName:(id)fp8;
- (id)languageName;
- (int)feedbackViewState;
- (void)resetInputLevelValues;
- (void)updateInputLevel:(id)fp8;
- (void)disableInputLevelMeter;
- (void)enableInputLevelMeter;
- (void)setFeedbackViewState:(int)fp8 withText:(id)fp12 cancelButtonTitle:(id)fp16 showingTryAgainButton:(BOOL)fp20;
- (void)setFeedbackViewState:(int)fp8;
- (BOOL)isLiveWaveformEnabled;
- (id)cautionImage;
- (id)micImage;
- (void)dealloc;
- (void)loadWindow;
- (id)initWithDelegate:(id)fp8 speechDelegate:(id)fp12 loader:(id)fp16 speechResourceLoader:(id)fp20;

@end

