/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface GIPWaveformView : _AudioQueueAllocateBuffer
{
    float *levelsArray_;
    unsigned int levelsArraySize_;
    BOOL scaleToFit_;
}

- (void)setScaleToFit:(BOOL)fp8;
- (BOOL)scaleToFit;
- (void)reloadView;
- (void)drawRect:(struct CGRect)fp8;
- (struct CGRect)rectForRange:(struct _NSRange)fp8;
- (void)setLevelsArray:(float *)fp8 ofSize:(int)fp12;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

