/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ShareToService.h"

@interface GooglePlusShareToService : ShareToService
{
}

+ (id)googlePlusService;
- (void)shareURL:(id)fp8 title:(id)fp12;
- (BOOL)shouldBeEnabled;
- (id)init;

@end

