/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class UIButton, UIFont;

@interface GridButton : _AudioQueueAllocateBuffer
{
    UIFont *textFont_;
    int maxNumberOfLines_;
    BOOL closeButtonVisible_;
    UIButton *closeButton_;
    struct CGPoint closeButtonLocation_;
    struct UIEdgeInsets imageInset_;
    struct UIEdgeInsets titleInset_;
    id <GridButtonDelegate> delegate_;
    struct ObjCPropertyReleaser propertyReleaser_GridButton_;
}

- (void)setTitleInset:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)titleInset;
- (void)setImageInset:(struct UIEdgeInsets)fp8;
- (struct UIEdgeInsets)imageInset;
- (void)setTextFont:(id)fp8;
- (id)textFont;
- (int)maxNumberOfLines;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)closeButtonVisible;
- (void)setCloseButtonLocation:(struct CGPoint)fp8;
- (struct CGPoint)closeButtonLocation;
- (void)setCloseButton:(id)fp8;
- (id)closeButton;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)accessibilityLabel;
- (void)closeButtonDidTap:(id)fp8;
- (void)setCloseButtonVisible:(BOOL)fp8;
- (struct CGRect)closeButtonRectForBounds:(struct CGRect)fp8;
- (void)setMaxNumberOfLines:(int)fp8;
- (struct CGRect)imageRectForContentRect:(struct CGRect)fp8;
- (struct CGRect)titleRectForContentRect:(struct CGRect)fp8;
- (void)layoutSubviews;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)setup;
- (id)initWithCoder:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

