/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface GTMFadeTruncatingLabel : _AudioQueueAllocateBuffer
{
    int truncateMode_;
}

- (void)setTruncateMode:(int)fp8;
- (int)truncateMode;
- (id)getLinearGradient:(struct CGRect)fp8;
- (void)drawTextInRect:(struct CGRect)fp8;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setup;

@end

