/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSMutableDictionary;

@interface GTMKeyValueObservingCenter : _AudioQueueAllocateBuffer
{
    NSMutableDictionary *observerHelpers_;
}

+ (id)defaultCenter;
- (void)removeObserver:(id)fp8 ofObject:(id)fp12 forKeyPath:(id)fp16 selector:(SEL)fp20;
- (void)addObserver:(id)fp8 ofObject:(id)fp12 forKeyPath:(id)fp16 selector:(SEL)fp20 userInfo:(id)fp24 options:(unsigned int)fp28;
- (id)dictionaryKeyForObserver:(id)fp8 ofObject:(id)fp12 forKeyPath:(id)fp16 selector:(SEL)fp20;
- (void)dealloc;
- (id)init;

@end

