/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NSCopying-Protocol.h"

@class NSDictionary, NSString;

@interface GTMKeyValueChangeNotification : _AudioQueueAllocateBuffer <NSCopying>
{
    NSString *keyPath_;
    id object_;
    id userInfo_;
    NSDictionary *change_;
}

- (id)change;
- (id)userInfo;
- (id)object;
- (id)keyPath;
- (unsigned int)hash;
- (id)description;
- (BOOL)isEqual:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)dealloc;
- (id)initWithKeyPath:(id)fp8 ofObject:(id)fp12 userInfo:(id)fp16 change:(id)fp20;

@end

