/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMLogger.h"

@interface GTMLogger (PrivateMethods)
- (void)logInternalFunc:(const char *)fp8 format:(id)fp12 valist:(void *)fp16 level:(int)fp20;
@end

