/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMLogBasicFormatter.h"

@class NSDateFormatter, NSString;

@interface GTMLogStandardFormatter : GTMLogBasicFormatter
{
    NSDateFormatter *dateFormatter_;
    NSString *pname_;
    int pid_;
}

- (id)stringForFunc:(id)fp8 withFormat:(id)fp12 valist:(void *)fp16 level:(int)fp20;
- (void)dealloc;
- (id)init;

@end

