/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMLogger.h"

@interface GTMLogger (GTMLoggerMacroHelpers)
- (void)logFuncAssert:(const char *)fp8 msg:(id)fp12;
- (void)logFuncError:(const char *)fp8 msg:(id)fp12;
- (void)logFuncInfo:(const char *)fp8 msg:(id)fp12;
- (void)logFuncDebug:(const char *)fp8 msg:(id)fp12;
@end

