/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GTMLogger.h"

#import "GTMLogWriter-Protocol.h"

@interface GTMLogger (GTMLoggerLogWriter) <GTMLogWriter>
- (void)logMessage:(id)fp8 level:(int)fp12;
@end

