/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class HttpProtocolHandler;

@interface HttpProtocolHandlerProxy : _AudioQueueAllocateBuffer
{
    HttpProtocolHandler *protocol_;
    struct scoped_nsobject<NSRecursiveLock> lock_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)cancelAuthenticationProxy;
- (void)setUserNameProxy:(id)fp8 password:(id)fp12;
- (void)didFinishLoadingClientProxy;
- (void)wasRedirectedToRequestClientProxy:(id)fp8 redirectResponse:(id)fp12;
- (void)didReceiveResponseClientProxy:(id)fp8;
- (void)didLoadDataClientProxy:(id)fp8;
- (void)didFailWithErrorClientProxy:(id)fp8;
- (void)invalidateProtocol;
- (id)initWithProtocol:(id)fp8;

@end

