/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "HttpLoginController-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@interface HttpLoginDialogController : _AudioQueueAllocateBuffer <HttpLoginController, UIAlertViewDelegate>
{
    struct scoped_nsobject<UIAlertView> loginDialog_;
    struct scoped_nsobject<HttpProtocolHandlerProxy> proxy_;
    struct scoped_refptr<net::AuthChallengeInfo> authInfo_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)passwordField;
- (id)userNameField;
- (id)newLoginDialog:(id)fp8 server:(id)fp12 okButtonLabel:(id)fp16 cancelButtonLabel:(id)fp20;
- (void)setUpLoginDialog;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)dismissCredentialRequest;
- (void)requestCredentials;
- (id)initWithProtocolHandlerProxy:(id)fp8 authInfo:(struct AuthChallengeInfo *)fp12;

@end

