/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface HttpProtocolHandler : _AudioQueueAllocateBuffer
{
    struct scoped_refptr<HttpProtocolHandlerCore> core_;
    struct scoped_nsobject<HttpProtocolHandlerProxy> protocol_proxy_;
    BOOL valid_scheme_;
}

+ (id)canonicalRequestForRequest:(id)fp8;
+ (BOOL)canInitWithRequest:(id)fp8;
+ (void)setHttpLoginControllerFactory:(id)fp8;
+ (void)setURLRequestContextGetter:(struct URLRequestContextGetter *)fp8;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (void)stopLoading;
- (void)startLoading;
- (id)cachedResponse;
- (id)initWithRequest:(id)fp8 cachedResponse:(id)fp12 client:(id)fp16;
- (void)cancelAuthentication;
- (void)setUserName:(id)fp8 password:(id)fp12;

@end

