/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "HtmlGenerator-Protocol.h"

@interface IdrHtmlGenerator : _AudioQueueAllocateBuffer <HtmlGenerator>
{
    int resourceId_;
    unsigned int encoding_;
}

- (void)generateHtml:(id)fp(null);
- (id)initWithResourceId:(int)fp8;
- (id)initWithResourceId:(int)fp8 encoding:(unsigned int)fp12;

@end

