/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NewTabPagePanelController.h"

@class UIWebView;

@interface IncognitoPanelController : NewTabPagePanelController
{
    UIWebView *webView_;
    struct ObjCPropertyReleaser propertyReleaser_IncognitoPanelController_;
}

- (void)setWebView:(id)fp8;
- (id)webView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)dealloc;
- (id)initWithLoader:(id)fp8 profile:(struct Profile *)fp12;

@end

