/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface InfoBarContainerView : _AudioQueueAllocateBuffer
{
}

- (float)topmostVisibleInfoBarHeight;
- (void)layoutSubviews;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)addInfoBar:(struct InfoBarIOS *)fp8 position:(int)fp12;

@end

