/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "UIWebViewDelegate-Protocol.h"

@interface Interstitial : _AudioQueueAllocateBuffer <UIWebViewDelegate>
{
    struct scoped_nsobject<NSString> title_;
    struct scoped_nsobject<NSURL> url_;
    struct scoped_nsobject<UIView> view_;
    struct scoped_nsobject<NSString> htmlContent_;
    id <InterstitialDelegate> delegate_;
}

+ (id)interstitialForTitle:(const struct basic_string<unsigned short, base::string16_char_traits, std::allocator<unsigned short>> *)fp8 description:(const struct basic_string<unsigned short, base::string16_char_traits, std::allocator<unsigned short>> *)fp12 extraInfo:(const struct vector<std::basic_string<char16, base::string16_char_traits>, std::allocator<std::basic_string<char16, base::string16_char_traits>>> *)fp16 onUrl:(const struct GURL *)fp20 recoverable:(BOOL)fp24;
+ (id)interstitialForSSLError:(const struct SSLErrorInfo *)fp8 onUrl:(const struct GURL *)fp12 recoverable:(BOOL)fp16;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)dismiss;
- (id)view;
- (void)setHtmlContent:(id)fp8;
- (id)htmlContent;
- (id)url;
- (id)title;
- (id)initWithTitle:(id)fp8 url:(id)fp12 html:(id)fp16;

@end

