/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface IOSSystemMonitorNotificationCatcher : _AudioQueueAllocateBuffer
{
    struct SystemMonitor *systemMonitor_;
}

- (void)didChangeState:(id)fp8;
- (void)dealloc;
- (id)initWithSystemMonitor:(struct SystemMonitor *)fp8;

@end

