/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NSCopying-Protocol.h"
#import "NSFastEnumeration-Protocol.h"
#import "NSMutableCopying-Protocol.h"

@interface JKArray : _AudioQueueAllocateBuffer <NSCopying, NSMutableCopying, NSFastEnumeration>
{
    id *objects;
    unsigned int count;
    unsigned int capacity;
    unsigned int mutations;
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (void)load;
- (id)mutableCopyWithZone:(struct _NSZone *)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (unsigned int)countByEnumeratingWithState:(CDAnonymousStruct1 *)fp8 objects:(id *)fp12 count:(unsigned int)fp16;
- (id)objectAtIndex:(unsigned int)fp8;
- (void)getObjects:(id *)fp8 range:(struct _NSRange)fp12;
- (unsigned int)count;
- (void)dealloc;

@end

