/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface JKMutableArray : _AudioQueueAllocateBuffer
{
}

+ (void)load;
- (id)mutableCopyWithZone:(struct _NSZone *)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)replaceObjectAtIndex:(unsigned int)fp8 withObject:(id)fp12;
- (void)removeObjectAtIndex:(unsigned int)fp8;
- (void)insertObject:(id)fp8 atIndex:(unsigned int)fp12;

@end

