/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "HttpLoginDialogController.h"

#import "UITextFieldDelegate-Protocol.h"

@interface LegacyHttpLoginDialogController : HttpLoginDialogController <UITextFieldDelegate>
{
    struct scoped_nsobject<UITextField> userNameField_;
    struct scoped_nsobject<UITextField> passwordField_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)passwordField;
- (id)userNameField;
- (id)newLoginDialog:(id)fp8 server:(id)fp12 okButtonLabel:(id)fp16 cancelButtonLabel:(id)fp20;
- (BOOL)textFieldShouldReturn:(id)fp8;
- (id)newTextFieldWithFrame:(struct CGRect)fp8;

@end

