/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class UIColor, UIFont;

@interface LinkLabel : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NSMutableArray> segments_;
    struct scoped_nsobject<NSMutableArray> actions_;
    struct scoped_nsobject<NSObject> noOp_;
    float position_;
    unsigned int index_;
    UIFont *font_;
    UIColor *textColor_;
    UIColor *linkColor_;
    struct ObjCPropertyReleaser propertyReleaser_LinkLabel_;
}

- (void)setLinkColor:(id)fp8;
- (id)linkColor;
- (void)setTextColor:(id)fp8;
- (id)textColor;
- (void)setFont:(id)fp8;
- (id)font;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)buildViewAtIndex:(unsigned int)fp8;
- (void)buildViews:(BOOL)fp8;
- (void)updateLinkColor:(id)fp8;
- (void)updateTextColor:(id)fp8;
- (void)updateFont:(id)fp8;
- (void)linkPressed:(id)fp8;
- (void)addTextSegment:(id)fp8;
- (void)addActionSegment:(id)fp8 action:(id)fp(null);
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;

@end

