/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol LocationBarDelegate
- (void)locationBarBeganEdit;
- (void)locationBarHasResignedFirstResponder;
- (void)locationBarHasBecomeFirstResponder;
- (void)loadGURLFromLocationBar:(const struct GURL *)fp8 referrer:(const struct GURL *)fp12 transition:(int)fp16;
@end

