/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ShareToService.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"

@interface MailShareToService : ShareToService <MFMailComposeViewControllerDelegate>
{
    struct scoped_nsobject<UIViewController> controller_;
}

+ (id)mailServiceWithController:(id)fp8;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)mailComposeController:(id)fp8 didFinishWithResult:(int)fp12 error:(id)fp16;
- (void)shareURL:(id)fp8 title:(id)fp12;
- (BOOL)shouldBeEnabled;
- (id)initWithController:(id)fp8;

@end

