/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NativeContent-Protocol.h"

@class NSString, NSURL, UIView;

@interface NativeContentController : _AudioQueueAllocateBuffer <NativeContent>
{
    UIView *view_;
    NSString *title_;
    NSURL *url_;
    struct ObjCPropertyReleaser propertyReleaser_NativeContentController_;
}

- (void)setUrl:(id)fp8;
- (id)url;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setView:(id)fp8;
- (id)view;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)reload;
- (BOOL)isViewAlive;
- (void)handleLowMemory;
- (void)dealloc;
- (id)initWithUrl:(id)fp8;
- (id)initWithNibName:(id)fp8 url:(id)fp12;

@end

