/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NativeContentController.h"

#import "NewTabPageBarDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSMutableDictionary, NewTabPagePanelController, NewTabPageView;

@interface NewTabPageController : NativeContentController <NewTabPageBarDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate>
{
    struct Profile *profile_;
    id <UrlLoader> loader_;
    id <SwipeRecognizerProvider> swipeRecognizerProvider_;
    NewTabPageView *newTabPageView_;
    struct scoped_nsobject<MostVisitedPanelController> mostVisitedController_;
    struct scoped_nsobject<BookmarkPanelController> bookmarkController_;
    struct scoped_nsobject<OpenTabsPanelController> openTabsController_;
    struct scoped_nsobject<IncognitoPanelController> incognitoController_;
    NewTabPagePanelController *currentController_;
    BOOL scrollInitialized_;
    NSMutableDictionary *dominantColorCache_;
    NSMutableDictionary *compositeCache_;
    struct ObjCPropertyReleaser propertyReleaser_NewTabPageController_;
}

- (id)swipeRecognizerProvider;
- (void)setNtpView:(id)fp8;
- (id)ntpView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)updateOverlayScrollPosition;
- (void)panelChanged:(id)fp8;
- (void)updateCurrentController:(id)fp8 index:(unsigned int)fp12;
- (void)scrollToPanel:(id)fp8 animate:(BOOL)fp12;
- (BOOL)loadPanel:(id)fp8;
- (void)loadControllerWithIndex:(unsigned int)fp8;
- (void)showPanel:(id)fp8;
- (void)selectPanel:(int)fp8;
- (void)newTabBarItemDidChange:(id)fp8 changePanel:(BOOL)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)setUpScrollView;
- (void)setSwipeRecognizerProvider:(id)fp8;
- (void)reload;
- (void)dealloc;
- (void)handleLowMemory;
- (id)initWithUrl:(id)fp8 loader:(id)fp12 profile:(struct Profile *)fp16 colorCache:(id)fp20 compositeCache:(id)fp24;

@end

