/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NewTabPageBar, UIScrollView;

@interface NewTabPageView : _AudioQueueAllocateBuffer
{
    NewTabPageBar *tabBar_;
    UIScrollView *scrollView_;
    struct ObjCPropertyReleaser propertyReleaser_NewTabPageView_;
}

- (void)setTabBar:(id)fp8;
- (id)tabBar;
- (void)setScrollView:(id)fp8;
- (id)scrollView;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)setFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithCoder:(id)fp8;

@end

