/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class UIView;

@interface NewTabPagePanelController : _AudioQueueAllocateBuffer
{
    struct Profile *profile_;
    id <UrlLoader> loader_;
    UIView *view_;
    struct ObjCPropertyReleaser propertyReleaser_NewTabPagePanelController_;
}

- (void)setView:(id)fp8;
- (id)view;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setUpGradientFade:(id)fp8 bottomView:(id)fp12;
- (void)reload;
- (id)initWithNibNamed:(id)fp8 loader:(id)fp12 profile:(struct Profile *)fp16;

@end

