/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSString, UIImage, UIView;

@interface NewTabPageBarItem : _AudioQueueAllocateBuffer
{
    NSString *title_;
    unsigned int identifier_;
    UIImage *image_;
    UIView *view_;
    struct ObjCPropertyReleaser propertyReleaser_NewTabPageBarItem_;
}

+ (id)newTabPageBarItemWithTitle:(id)fp8 identifier:(unsigned int)fp12 image:(id)fp16;
- (void)setView:(id)fp8;
- (id)view;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setIdentifier:(unsigned int)fp8;
- (unsigned int)identifier;
- (void)setTitle:(id)fp8;
- (id)title;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)init;

@end

