/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, UIButton;

@interface NewTabPageBar : _AudioQueueAllocateBuffer <UIGestureRecognizerDelegate>
{
    NSArray *buttons_;
    NSArray *items_;
    unsigned int selectedIndex_;
    UIButton *popupButton_;
    BOOL canAnimate_;
    id <NewTabPageBarDelegate> delegate_;
    struct scoped_nsobject<UIImageView> logoView_;
    struct scoped_nsobject<UIImageView> overlayView_;
    float buttonWidth_;
    float buttonLeft_;
    float overlayPercentage_;
    struct ObjCPropertyReleaser propertyReleaser_NewTabPageBar_;
}

- (float)overlayPercentage;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setButtons:(id)fp8;
- (id)buttons;
- (void)setPopupButton:(id)fp8;
- (id)popupButton;
- (unsigned int)selectedIndex;
- (id)items;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)dealloc;
- (void)showDescriptiveTextPopup;
- (void)hidePopup;
- (void)orientationChanged:(id)fp8;
- (void)barTapEnd:(id)fp8;
- (void)buttonDidTap:(id)fp8;
- (void)setSelectedIndex:(unsigned int)fp8;
- (void)setupButton:(id)fp8 item:(id)fp12;
- (void)setOverlayPercentage:(float)fp8;
- (void)setItems:(id)fp8;
- (void)calculateButtonWidth;
- (void)layoutSubviews;
- (void)setup;
- (id)initWithCoder:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

