/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NIAttributedLabel.h"

@interface NIAttributedLabel (ConversionUtilities)
+ (id)mutableAttributedStringFromLabel:(id)fp8;
+ (unsigned char)lineBreakModeFromUILineBreakMode:(int)fp8;
+ (unsigned char)alignmentFromUITextAlignment:(int)fp8;
@end

