/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSArray, NSMutableArray, NSMutableAttributedString, NSTextCheckingResult, UIColor;

@interface NIAttributedLabel : _AudioQueueAllocateBuffer
{
    NSMutableAttributedString *_attributedString;
    struct __CTFrame *_textFrame;
    BOOL _linksHaveBeenDetected;
    NSArray *_detectedlinkLocations;
    NSMutableArray *_explicitLinkLocations;
    NSTextCheckingResult *_touchedLink;
    BOOL _autoDetectLinks;
    UIColor *_linkColor;
    UIColor *_linkHighlightColor;
    float _strokeWidth;
    UIColor *_strokeColor;
    float _textKern;
    int _underlineStyle;
    int _underlineStyleModifier;
    id <NIAttributedLabelDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (float)textKern;
- (id)strokeColor;
- (float)strokeWidth;
- (int)underlineStyleModifier;
- (int)underlineStyle;
- (BOOL)autoDetectLinks;
- (void)drawTextInRect:(struct CGRect)fp8;
- (id)mutableAttributedStringWithLinkStylesApplied;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (id)linkAtPoint:(struct CGPoint)fp8;
- (id)linkAtIndex:(long)fp8;
- (struct CGRect)getLineBounds:(struct __CTLine *)fp8 point:(struct CGPoint)fp12;
- (void)detectLinks;
- (void)setLinkHighlightColor:(id)fp8;
- (id)linkHighlightColor;
- (void)setLinkColor:(id)fp8;
- (id)linkColor;
- (void)setTextKern:(float)fp8 range:(struct _NSRange)fp12;
- (void)setTextKern:(float)fp8;
- (void)setStrokeColor:(id)fp8 range:(struct _NSRange)fp12;
- (void)setStrokeColor:(id)fp8;
- (void)setStrokeWidth:(float)fp8 range:(struct _NSRange)fp12;
- (void)setStrokeWidth:(float)fp8;
- (void)setUnderlineStyle:(int)fp8 modifier:(int)fp12 range:(struct _NSRange)fp16;
- (void)setUnderlineStyleModifier:(int)fp8;
- (void)setUnderlineStyle:(int)fp8;
- (void)setFont:(id)fp8 range:(struct _NSRange)fp12;
- (void)setFont:(id)fp8;
- (void)setTextColor:(id)fp8 range:(struct _NSRange)fp12;
- (void)setTextColor:(id)fp8;
- (void)setLineBreakMode:(int)fp8;
- (void)setTextAlignment:(int)fp8;
- (void)removeAllExplicitLinks;
- (void)addLink:(id)fp8 range:(struct _NSRange)fp12;
- (void)setAutoDetectLinks:(BOOL)fp8;
- (void)setAttributedString:(id)fp8;
- (id)attributedString;
- (void)setText:(id)fp8;
- (struct CGSize)sizeThatFits:(struct CGSize)fp8;
- (void)setBounds:(struct CGRect)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)attributedTextDidChange;
- (void)resetTextFrame;
- (void)awakeFromNib;
- (void)dealloc;

@end

