/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NIMemoryCache.h"

@interface NIImageMemoryCache : NIMemoryCache
{
    unsigned int _numberOfPixels;
    unsigned int _maxNumberOfPixels;
    unsigned int _maxNumberOfPixelsUnderStress;
}

- (void)setMaxNumberOfPixelsUnderStress:(unsigned int)fp8;
- (unsigned int)maxNumberOfPixelsUnderStress;
- (void)setMaxNumberOfPixels:(unsigned int)fp8;
- (unsigned int)maxNumberOfPixels;
- (void)setNumberOfPixels:(unsigned int)fp8;
- (unsigned int)numberOfPixels;
- (void)willRemoveObject:(id)fp8 withName:(id)fp12;
- (void)didSetObject:(id)fp8 withName:(id)fp12;
- (BOOL)willSetObject:(id)fp8 withName:(id)fp12 previousObject:(id)fp16;
- (void)reduceMemoryUsage;
- (void)removeAllObjects;
- (unsigned int)numberOfPixelsUsedByImage:(id)fp8;

@end

