/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"
#import "NSFastEnumeration-Protocol.h"

@interface NILinkedList : _AudioQueueAllocateBuffer <NSCopying, NSCoding, NSFastEnumeration>
{
    struct NILinkedListNode *_head;
    struct NILinkedListNode *_tail;
    unsigned long _modificationNumber;
    unsigned int _count;
}

+ (id)linkedListWithArray:(id)fp8;
+ (id)linkedList;
- (struct NILinkedListNode *)head;
- (void)setCount:(unsigned int)fp8;
- (unsigned int)count;
- (void)removeLastObject;
- (void)removeFirstObject;
- (void)removeObject:(id)fp8;
- (void)removeAllObjects;
- (void)addObjectsFromArray:(id)fp8;
- (void *)addObject:(id)fp8;
- (void)removeObjectAtLocation:(void *)fp8;
- (void *)locationOfObject:(id)fp8;
- (id)objectEnumerator;
- (id)objectAtLocation:(void *)fp8;
- (id)description;
- (BOOL)containsObject:(id)fp8;
- (id)allObjects;
- (id)lastObject;
- (id)firstObject;
- (unsigned int)countByEnumeratingWithState:(CDAnonymousStruct1 *)fp8 objects:(id *)fp12 count:(unsigned int)fp16;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)_eraseNode:(struct NILinkedListNode *)fp8;
- (id)initWithArray:(id)fp8;
- (void)dealloc;

@end

