/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface Nimbus : _AudioQueueAllocateBuffer
{
}

+ (id)networkOperationQueue;
+ (void)setNetworkOperationQueue:(id)fp8;
+ (id)imageMemoryCache;
+ (void)setImageMemoryCache:(id)fp8;

@end

