/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NILinkedList, NSMutableDictionary;

@interface NIMemoryCache : _AudioQueueAllocateBuffer
{
    NSMutableDictionary *_cacheMap;
    NILinkedList *_lruCacheObjects;
}

- (void)setLruCacheObjects:(id)fp8;
- (id)lruCacheObjects;
- (void)setCacheMap:(id)fp8;
- (id)cacheMap;
- (unsigned int)count;
- (void)reduceMemoryUsage;
- (void)removeAllObjects;
- (void)removeObjectWithName:(id)fp8;
- (id)nameOfMostRecentlyUsedObject;
- (id)nameOfLeastRecentlyUsedObject;
- (id)dateOfLastAccessWithName:(id)fp8;
- (BOOL)containsObjectWithName:(id)fp8;
- (id)objectWithName:(id)fp8;
- (void)storeObject:(id)fp8 withName:(id)fp12 expiresAfter:(id)fp16;
- (void)storeObject:(id)fp8 withName:(id)fp12;
- (void)willRemoveObject:(id)fp8 withName:(id)fp12;
- (void)didSetObject:(id)fp8 withName:(id)fp12;
- (BOOL)willSetObject:(id)fp8 withName:(id)fp12 previousObject:(id)fp16;
- (void)removeCacheInfoForName:(id)fp8;
- (void)setCacheInfo:(id)fp8 forName:(id)fp12;
- (id)cacheInfoForName:(id)fp8;
- (void)updateAccessTimeForInfo:(id)fp8;
- (id)initWithCapacity:(unsigned int)fp8;
- (id)init;
- (void)dealloc;

@end

