/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSDate, NSString;

@interface NIMemoryCacheInfo : _AudioQueueAllocateBuffer
{
    NSString *_name;
    id _object;
    NSDate *_expirationDate;
    NSDate *_lastAccessTime;
    void *_lruLocation;
}

- (void)setLruLocation:(void *)fp8;
- (void *)lruLocation;
- (void)setLastAccessTime:(id)fp8;
- (id)lastAccessTime;
- (void)setExpirationDate:(id)fp8;
- (id)expirationDate;
- (void)setObject:(id)fp8;
- (id)object;
- (void)setName:(id)fp8;
- (id)name;
- (BOOL)hasExpired;
- (void)dealloc;

@end

