/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface NINavigationAppearanceSnapshot : _AudioQueueAllocateBuffer
{
    BOOL _navBarTranslucent;
    int _navBarStyle;
    int _statusBarStyle;
}

- (int)statusBarStyle;
- (int)navBarStyle;
- (BOOL)navBarTranslucent;
- (void)restoreForNavigationController:(id)fp8 animated:(BOOL)fp12;
- (id)initForNavigationController:(id)fp8;

@end

