/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface NINavigationAppearance : _AudioQueueAllocateBuffer
{
}

+ (void)clear;
+ (int)count;
+ (void)popAppearanceForNavigationController:(id)fp8 animated:(BOOL)fp12;
+ (void)pushAppearanceForNavigationController:(id)fp8;

@end

