/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NIOperation.h"

@class NSData, NSURL;

@interface NINetworkRequestOperation : NIOperation
{
    NSURL *_url;
    double _timeout;
    NSData *_data;
    id _processedObject;
    unsigned int _cachePolicy;
}

- (void)setProcessedObject:(id)fp8;
- (id)processedObject;
- (void)setData:(id)fp8;
- (id)data;
- (void)setCachePolicy:(unsigned int)fp8;
- (unsigned int)cachePolicy;
- (void)setTimeout:(double)fp8;
- (double)timeout;
- (void)setUrl:(id)fp8;
- (id)url;
- (void)main;
- (id)initWithURL:(id)fp8;
- (void)dealloc;

@end

