/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSError;

@interface NIOperation : _AudioQueueAllocateBuffer
{
    id <NIOperationDelegate> _delegate;
    int _tag;
    NSError *_lastError;
    id _didStartBlock;
    id _didFinishBlock;
    id _didFailWithErrorBlock;
    id _willFinishBlock;
}

- (void)setWillFinishBlock:(id)fp(null);
- (id)willFinishBlock;
- (void)setDidFailWithErrorBlock:(id)fp(null);
- (id)didFailWithErrorBlock;
- (void)setDidFinishBlock:(id)fp(null);
- (id)didFinishBlock;
- (void)setDidStartBlock:(id)fp(null);
- (id)didStartBlock;
- (void)setLastError:(id)fp8;
- (id)lastError;
- (void)setTag:(int)fp8;
- (int)tag;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)onMainThreadOperationDidFailWithError:(id)fp8;
- (void)onMainThreadOperationDidFinish;
- (void)onMainThreadOperationDidStart;
- (void)willFinish;
- (void)didFailWithError:(id)fp8;
- (void)didFinish;
- (void)didStart;
- (void)dealloc;

@end

