/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSMutableDictionary;

@interface NIViewRecycler : _AudioQueueAllocateBuffer
{
    NSMutableDictionary *_reuseIdentifiersToRecycledViews;
}

- (void)removeAllViews;
- (void)recycleView:(id)fp8;
- (id)dequeueReusableViewWithIdentifier:(id)fp8;
- (void)reduceMemoryUsage;
- (id)init;
- (void)dealloc;

@end

