/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface NonRecursiveMemoryUnarchiver : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NSArray> archive_;
    int archiveIndex_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)decodeDataObject;
- (void)decodeValueOfObjCType:(const char *)fp8 at:(void *)fp12;
- (int)versionForClassName:(id)fp8;
- (BOOL)allowsKeyedCoding;
- (id)decodeObjectWithClass:(Class)fp8;
- (id)initForReadingWithArray:(id)fp8;

@end

