/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class UIView;

@interface NoTabsController : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NoTabsToolbarController> toolbarController_;
    UIView *parentView_;
    struct scoped_nsobject<UIView> backgroundView_;
    struct scoped_nsobject<UIImageView> modeToggleImageView_;
    struct CGRect toggleImageEndFrame_;
    struct ObjCPropertyReleaser propertyReleaser_NoTabsController_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)installNoTabsAnimationToggleImageForButton:(id)fp8 inView:(id)fp12;
- (struct CGRect)imageFrameForButton:(id)fp8 inView:(id)fp12;
- (void)installNoTabsBackgroundInView:(id)fp8;
- (void)installNoTabsToolbarInView:(id)fp8;
- (void)dismissAnimationDidFinish;
- (void)dismissNoTabsUI;
- (void)prepareForDismissAnimation;
- (void)showAnimationDidFinish;
- (void)showNoTabsUI;
- (void)prepareForShowAnimation;
- (void)dismissToolsMenuPopup;
- (void)showToolsMenuPopup;
- (void)installAnimationImageForButton:(id)fp8 inView:(id)fp12 show:(BOOL)fp16;
- (void)setHasModeToggleSwitch:(BOOL)fp8;
- (id)initWithView:(id)fp8;

@end

