/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ToolbarController.h"

@class UIButton, UIView;

@interface NoTabsToolbarController : ToolbarController
{
    UIView *noTabsToolbar_;
    UIButton *buttonNewTab_;
    UIButton *modeToggleButton_;
    struct ObjCPropertyReleaser propertyReleaser_NoTabsToolbarController_;
}

- (void)setModeToggleButton:(id)fp8;
- (id)modeToggleButton;
- (void)setButtonNewTab:(id)fp8;
- (id)buttonNewTab;
- (void)setNoTabsToolbar:(id)fp8;
- (id)noTabsToolbar;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)recordUserMetrics:(id)fp8;
- (void)setHasModeToggleSwitch:(BOOL)fp8;
- (void)setControlsTransform:(struct CGAffineTransform)fp8;
- (id)init;

@end

