/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSString, UIColor;

@interface OmniboxTextFieldIOS : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NSAttributedString> attributedText_;
    struct scoped_nsobject<SelectedTextLabel> selection_;
    UIColor *defaultColor_;
    float imageInset_;
    struct scoped_nsobject<SelectedTextLabel> preEditStaticLabel_;
    NSString *preEditText_;
    BOOL animatingEVCert_;
    struct scoped_nsobject<NSAttributedString> savedAttributedText_;
    struct scoped_nsobject<NSString> savedPlaceholderText_;
}

- (void)setAnimatingEVCert:(BOOL)fp8;
- (BOOL)animatingEVCert;
- (void)setPreEditText:(id)fp8;
- (id)preEditText;
- (void)setDefaultColor:(id)fp8;
- (id)defaultColor;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)paste:(id)fp8;
- (void)copy:(id)fp8;
- (void)stopAllAnimations;
- (void)animateEVCertForName:(id)fp8;
- (void)hidePlaceholderImage;
- (void)showPlaceholderImage;
- (void)setPlaceholderImage:(int)fp8;
- (struct CGRect)leftViewRectForBounds:(struct CGRect)fp8;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)drawTextInRect:(struct CGRect)fp8;
- (struct CGRect)editingRectForBounds:(struct CGRect)fp8;
- (struct CGRect)textRectForBounds:(struct CGRect)fp8;
- (struct CGRect)clearButtonRectForBounds:(struct CGRect)fp8;
- (id)markedText;
- (void)clearAutocompleteText;
- (BOOL)hasAutocompleteText;
- (void)setText:(id)fp8 userTextLength:(unsigned long)fp12;
- (void)setText:(id)fp8;
- (void)setTextInternal:(id)fp8 autocompleteText:(id)fp12;
- (void)useImage:(int)fp8;
- (void)createSelectionViewIfNecessary;
- (struct basic_string<unsigned short, base::string16_char_traits, std::allocator<unsigned short>>)autocompleteText;
- (struct basic_string<unsigned short, base::string16_char_traits, std::allocator<unsigned short>>)displayedText;
- (BOOL)isPreEditing;
- (void)exitPreEditState;
- (void)layoutSubviews;
- (void)enterPreEditState;
- (struct CGRect)preEditLabelRectForBounds:(struct CGRect)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)awakeFromNib;
- (void)insertText:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;

@end

