/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSMutableAttributedString;

@interface OmniboxPopupTruncatingLabel : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<CATextLayer> textLayer_;
    struct scoped_nsobject<UIImage> gradient_;
    struct ObjCPropertyReleaser propertyReleaser_OmniboxPopupTruncatingLabel_;
    int truncateMode_;
    NSMutableAttributedString *attributedText_;
    BOOL highlighted_;
    NSMutableAttributedString *highlightedText_;
}

- (void)setHighlightedText:(id)fp8;
- (id)highlightedText;
- (void)setHighlighted:(BOOL)fp8;
- (BOOL)highlighted;
- (void)setAttributedText:(id)fp8;
- (id)attributedText;
- (void)setTruncateMode:(int)fp8;
- (int)truncateMode;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)getLinearGradient:(struct CGRect)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setup;

@end

