/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class OmniboxPopupTruncatingLabel;

@interface OmniboxPopupTableViewCell : _AudioQueueAllocateBuffer
{
    struct ObjCPropertyReleaser propertyReleaser_OmniboxPopupTableViewCell_;
    OmniboxPopupTruncatingLabel *textTruncatingLabel_;
    OmniboxPopupTruncatingLabel *detailTruncatingLabel_;
}

- (void)setDetailTruncatingLabel:(id)fp8;
- (id)detailTruncatingLabel;
- (void)setTextTruncatingLabel:(id)fp8;
- (id)textTruncatingLabel;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setHighlighted:(BOOL)fp8 animated:(BOOL)fp12;
- (id)initWithStyle:(int)fp8 reuseIdentifier:(id)fp12;

@end

