/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NewTabPagePanelController.h"

#import "SyncObserverModelBridge-Protocol.h"

@interface OpenTabsPanelController : NewTabPagePanelController <SyncObserverModelBridge>
{
    struct scoped_ptr<OpenTabsPanel::ChangeListenerBridge> bridge_;
    struct scoped_nsobject<NewTabPagePanelController> controller_;
    int userState_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)hasForeignSessions;
- (BOOL)isSyncTabsEnabled;
- (BOOL)isSignedIn;
- (void)onStateChanged;
- (id)newPanelView;
- (void)addPanelView;
- (int)userSignedInState;
- (void)reloadPanel;
- (void)reload;
- (void)reloadSessions;
- (id)initWithLoader:(id)fp8 profile:(struct Profile *)fp12;

@end

