/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface OpenUrlCommand : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NSURL> url_;
    struct scoped_nsobject<NSURL> referrer_;
    struct scoped_nsobject<NSString> windowName_;
    BOOL inIncognito_;
    BOOL inBackground_;
    BOOL fromChrome_;
    int appendTo_;
    int tag_;
}

- (BOOL)fromChrome;
- (void)setTag:(int)fp8;
- (int)tag;
- (id).cxx_construct;
- (void).cxx_destruct;
- (int)appendTo;
- (BOOL)inBackground;
- (BOOL)inIncognito;
- (id)windowName;
- (id)referrer;
- (id)url;
- (id)initWithUrlFromChrome:(id)fp8;
- (id)initWithUrl:(id)fp8 referrer:(id)fp12 windowName:(id)fp16 inIncognito:(BOOL)fp20 inBackground:(BOOL)fp24 appendTo:(int)fp28;

@end

