/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface PageInfoView : _AudioQueueAllocateBuffer
{
    struct CGPoint arrowPosition_;
    struct CGPath *path_;
    struct CGPath *innerPath_;
}

- (struct CGPoint)arrowPosition;
- (id).cxx_construct;
- (struct CGPath *)newPathForRect:(struct CGRect)fp8;
- (struct CGPath *)borderPath;
- (struct CGPath *)innerBorderPath;
- (struct CGRect)rectangleBounds;
- (struct CGRect)contentFrame;
- (void)drawRect:(struct CGRect)fp8;
- (void)setArrowPosition:(struct CGPoint)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)dealloc;

@end

