/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NativeContentController.h"

@class UILabel, UITextView;

@interface PageNotAvailableController : NativeContentController
{
    UILabel *titleLabel_;
    UITextView *descriptionView_;
    struct ObjCPropertyReleaser propertyReleaser_PageNotAvailableController_;
}

- (void)setDescriptionView:(id)fp8;
- (id)descriptionView;
- (void)setTitleLabel:(id)fp8;
- (id)titleLabel;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithUrl:(id)fp8;

@end

