/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "OmniboxPopupTableViewController.h"

@interface PopupTableViewController : OmniboxPopupTableViewController
{
    struct OmniboxPopupViewIOS *popupView_;
    struct AutocompleteResult currentResult_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)acceptRow:(unsigned int)fp8;
- (void)copyRowToOmnibox:(unsigned int)fp8;
- (BOOL)isAppendQueryEnabled:(unsigned int)fp8;
- (id)getLeftImage:(unsigned int)fp8;
- (const struct vector<AutocompleteMatch::ACMatchClassification, std::allocator<AutocompleteMatch::ACMatchClassification>> *)getDetailTextClassifications:(unsigned int)fp8;
- (id)getDetailText:(unsigned int)fp8;
- (const struct vector<AutocompleteMatch::ACMatchClassification, std::allocator<AutocompleteMatch::ACMatchClassification>> *)getTextClassifications:(unsigned int)fp8;
- (id)getText:(unsigned int)fp8;
- (BOOL)isSearchMatch:(const int *)fp8;
- (unsigned int)dataSourceIndexToDisplayRowNumber:(unsigned int)fp8;
- (unsigned int)numberOfRows;
- (void)scrollViewDidScroll:(id)fp8;
- (void)updateMatches:(const struct AutocompleteResult *)fp8;
- (BOOL)compareMatchResults:(const struct AutocompleteResult *)fp8 withResults:(const struct AutocompleteResult *)fp12 atIndex:(int)fp16;
- (BOOL)compareMatchClassifications:(const struct vector<AutocompleteMatch::ACMatchClassification, std::allocator<AutocompleteMatch::ACMatchClassification>> *)fp8 withClassifications:(const struct vector<AutocompleteMatch::ACMatchClassification, std::allocator<AutocompleteMatch::ACMatchClassification>> *)fp12;
- (id)initWithPopupView:(struct OmniboxPopupViewIOS *)fp8;

@end

