/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol PrerenderProvider
- (void)cancelPrerender;
- (void)prerenderURL:(const struct GURL *)fp8 transition:(int)fp12 immediately:(BOOL)fp16;
@end

