/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PrerenderDelegate-Protocol.h"

@protocol RequestTrackerDelegate <PrerenderDelegate>
- (void)clearCertificates;
- (void)certificateUsed:(struct X509Certificate *)fp8 forHost:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp12;
- (void)updatedProgress:(float)fp8;
- (void)presentSSLError:(const struct SSLErrorInfo *)fp8 forSSLStatus:(const struct SSLStatus *)fp12 onUrl:(const struct GURL *)fp16 recoverable:(BOOL)fp20 callback:(id)fp(null);
- (void)handleXAutoLogin:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp8;
- (void)updatedSSLStatus:(const struct SSLStatus *)fp8 forPageUrl:(const struct GURL *)fp12 userInfo:(id)fp16;
@end

