/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class CAGradientLayer;

@interface ResizingGradientView : _AudioQueueAllocateBuffer
{
    CAGradientLayer *gradientLayer_;
    struct ObjCPropertyReleaser propertyReleaser_ResizingGradientView_;
}

- (void)setGradientLayer:(id)fp8;
- (id)gradientLayer;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)setup;

@end

