/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface ResubmitDataActionSheet : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NSMutableURLRequest> request_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)getRequest;
- (id)initWithRequest:(id)fp8 delegate:(id)fp12;

@end

