/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FancyButton.h"

#import "FancyButtonDelegate-Protocol.h"

@interface SecondaryActionButton : FancyButton <FancyButtonDelegate>
{
}

- (id)disabledTextColor;
- (id)highlightTextColor;
- (id)normalTextColor;
- (struct UIEdgeInsets)capInsets;
- (id)imageName;

@end

