/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface SelectedTextLabel : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NSString> fieldText_;
    struct scoped_nsobject<NSString> selectedText_;
    float clipSize_;
    float stringSize_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)drawTextInRect:(struct CGRect)fp8;
- (void)setFieldText:(id)fp8 selectedText:(id)fp12;
- (void)setText:(id)fp8;
- (id)selectedText;
- (id)displayedText;

@end

