/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSData, NSDictionary, NSString, NSURL;

@interface SessionEntry : _AudioQueueAllocateBuffer <NSCoding, NSCopying>
{
    int index_;
    NSURL *originalUrl_;
    NSDictionary *state_;
    NSDictionary *httpHeaders_;
    NSData *POSTData_;
    NSString *serializedStateObject_;
    BOOL createdFromPushState_;
    BOOL useDesktopUserAgent_;
    struct scoped_ptr<content::NavigationEntry> navigationEntry_;
    struct ObjCPropertyReleaser propertyReleaser_SessionEntry_;
    BOOL rendererInitiated_;
}

- (void)setRendererInitiated:(BOOL)fp8;
- (BOOL)rendererInitiated;
- (void)setCreatedFromPushState:(BOOL)fp8;
- (BOOL)createdFromPushState;
- (void)setSerializedStateObject:(id)fp8;
- (id)serializedStateObject;
- (void)setIndex:(int)fp8;
- (int)index;
- (void)setState:(id)fp8;
- (id)state;
- (void)setUseDesktopUserAgent:(BOOL)fp8;
- (BOOL)useDesktopUserAgent;
- (void)setOriginalUrl:(id)fp8;
- (id)originalUrl;
- (void)setHttpHeaders:(id)fp8;
- (id)httpHeaders;
- (void)setPOSTData:(id)fp8;
- (id)POSTData;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setTransition:(int)fp8;
- (int)transition;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setReferrer:(id)fp8;
- (id)referrer;
- (void)setVirtualUrl:(id)fp8;
- (id)virtualUrl;
- (void)setUrl:(id)fp8;
- (id)url;
- (struct NavigationEntry *)navigationEntry;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithNavigation:(const struct TabNavigation *)fp8;
- (id)initWithUrl:(id)fp8 referrer:(id)fp12 transition:(int)fp16 useDesktopUserAgent:(BOOL)fp20 rendererInitiated:(BOOL)fp24;

@end

