/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface SessionServiceIOS : _AudioQueueAllocateBuffer
{
    struct dispatch_queue_s *fileIOQueue_;
    struct scoped_nsobject<NSMutableDictionary> pendingWindows_;
}

+ (id)sharedService;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)deleteLastSession:(id)fp8;
- (id)loadWindowFromPath:(id)fp8;
- (id)loadWindowFromDirectory:(id)fp8;
- (void)saveWindow:(id)fp8 toDirectory:(id)fp12 immediately:(BOOL)fp16;
- (void)performSaveWindow:(id)fp8 toDirectory:(id)fp12;
- (void)performSaveToDirectoryInBackground:(id)fp8;
- (id)sessionFilePathForDirectory:(id)fp8;
- (void)dealloc;
- (id)init;

@end

