/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NSCoding-Protocol.h"

@class NSArray;

@interface SessionWindowIOS : _AudioQueueAllocateBuffer <NSCoding>
{
    unsigned int selectedIndex_;
    NSArray *sessions_;
    struct ObjCPropertyReleaser propertyReleaser_SessionWindow_;
}

- (void)setSessions:(id)fp8;
- (id)sessions;
- (unsigned int)selectedIndex;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)description;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithSessions:(id)fp8 currentIndex:(unsigned int)fp12;

@end

