/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@interface SessionCertificatePolicyManager : _AudioQueueAllocateBuffer <NSCoding, NSCopying>
{
    // Error parsing type: {set<<anonymous>::AllowedCertificate, <anonymous>::LessThan, std::allocator<<anonymous>::AllowedCertificate> >="_M_t"{_Rb_tree<<anonymous>::AllowedCertificate, <anonymous>::AllowedCertificate, std::_Identity<<anonymous>::AllowedCertificate>, <anonymous>::LessThan, std::allocator<<anonymous>::AllowedCertificate> >="_M_impl"{_Rb_tree_impl<<anonymous>::LessThan, false>="_M_key_compare"{LessThan="certificateCompare_"{LessThan=}}"_M_header"{_Rb_tree_node_base="_M_color"i"_M_parent"^{_Rb_tree_node_base}"_M_left"^{_Rb_tree_node_base}"_M_right"^{_Rb_tree_node_base}}"_M_node_count"I}}}, name: allowed_
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)toSSLHostState:(struct Profile *)fp8;
- (void)clearCertificates;
- (void)registerAllowedCertificate:(struct X509Certificate *)fp8 forHost:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp12;

@end

