/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSMutableArray, NSString, SessionCertificatePolicyManager;

@interface SessionController : _AudioQueueAllocateBuffer <NSCoding, NSCopying>
{
    NSString *tabId_;
    NSString *openerId_;
    int openerNavigationIndex_;
    int currentNavigationIndex_;
    int previousNavigationIndex_;
    NSMutableArray *entries_;
    struct scoped_nsobject<SessionEntry> pending_entry_;
    NSString *windowName_;
    SessionCertificatePolicyManager *sessionCertificatePolicyManager_;
    double lastVisitedTimestamp_;
    BOOL useDesktopUserAgentForNextPendingEntry_;
    struct ObjCPropertyReleaser propertyReleaser_SessionController_;
}

- (void)setSessionCertificatePolicyManager:(id)fp8;
- (id)sessionCertificatePolicyManager;
- (int)openerNavigationIndex;
- (id)openerId;
- (void)setLastVisitedTimestamp:(double)fp8;
- (double)lastVisitedTimestamp;
- (void)setWindowName:(id)fp8;
- (id)windowName;
- (void)setEntries:(id)fp8;
- (id)entries;
- (int)previousNavigationIndex;
- (int)currentNavigationIndex;
- (void)setTabId:(id)fp8;
- (id)tabId;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)uniqueID;
- (void)useDesktopUserAgentForNextPendingEntry;
- (id)lastUserEntry;
- (BOOL)isPushStateNavigationBetweenEntry:(id)fp8 andEntry:(id)fp12;
- (id)currentRedirectedUrls;
- (void)goDelta:(int)fp8;
- (void)goForward;
- (void)goBack;
- (BOOL)canGoForward;
- (BOOL)canGoBack;
- (void)copyStateFromAndPrune:(id)fp8;
- (BOOL)hasPendingEntry;
- (void)discardNonCommittedEntries;
- (void)updateCurrentEntryWithURL:(id)fp8 stateObject:(id)fp12;
- (void)pushNewEntryWithURL:(id)fp8 stateObject:(id)fp12;
- (void)commitPendingEntry;
- (void)clearForwardEntries;
- (void)updatePendingEntry:(id)fp8;
- (void)addPendingEntry:(id)fp8 referrer:(id)fp12 transition:(int)fp16 rendererInitiated:(BOOL)fp20;
- (id)previousEntry;
- (id)visibleEntry;
- (id)currentEntry;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (id)initWithNavigations:(const struct vector<TabNavigation, std::allocator<TabNavigation>> *)fp8 currentIndex:(unsigned int)fp12;
- (id)initWithWindowName:(id)fp8 openerId:(id)fp12 openerNavigationIndex:(int)fp16;

@end

