/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface SettingsNavigationController : _AudioQueueAllocateBuffer
{
    struct Profile *profile_;
    id completionTarget_;
    SEL completionAction_;
    BOOL commitSyncOnClose_;
    struct scoped_ptr<SyncInitialSetupController> syncSetupController_;
}

+ (id)newSyncEncryptionPassphraseNavigationController:(struct Profile *)fp8 completionTarget:(id)fp12 completionAction:(SEL)fp16;
+ (id)newUpdateSignInNavigationController:(struct Profile *)fp8 completionTarget:(id)fp12 completionAction:(SEL)fp16;
+ (id)newSignInToChromeNavigationController:(struct Profile *)fp8 completionTarget:(id)fp12 completionAction:(SEL)fp16;
+ (id)newSettingsNavigationController:(struct Profile *)fp8 userFeedbackDataSource:(id)fp12 completionTarget:(id)fp16 completionAction:(SEL)fp20;
- (void)setCommitSyncOnClose:(BOOL)fp8;
- (BOOL)commitSyncOnClose;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)cancelSettings;
- (void)closeSettings;
- (void)commitSyncChanges;
- (BOOL)disablesAutomaticKeyboardDismissal;
- (id)popViewControllerAnimated:(BOOL)fp8;
- (void)addCancelButton;
- (void)addDoneButton;
- (void)configureUI;
- (id)initForSignInPageWithProfile:(struct Profile *)fp8 completionTarget:(id)fp12 completionAction:(SEL)fp16;
- (id)initWithRootViewController:(id)fp8 profile:(struct Profile *)fp12 completionTarget:(id)fp16 completionAction:(SEL)fp20;

@end

