/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NIAttributedLabelDelegate-Protocol.h"

@interface SettingsLinkController : _AudioQueueAllocateBuffer <NIAttributedLabelDelegate>
{
    struct scoped_nsobject<SettingsMultiLabelView> view_;
}

+ (id)newGoogleDashboardController;
+ (id)newCannotAccessAccountController;
+ (id)newAspLearnMoreAndCannotAccessAccountController;
+ (id)newCreateAndCannotAccessAccountController;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)attributedLabel:(id)fp8 didSelectLink:(id)fp12 atPoint:(struct CGPoint)fp16;
- (void)addLinkLabelWithIdsTitle:(int)fp8 idsUrl:(int)fp12;
- (void)addLinkLabelWithIdsTitle:(int)fp8 url:(const char *)fp12;
- (void)addLinkLabelWithTitle:(id)fp8 url:(id)fp12;
- (id)view;
- (id)init;

@end

