/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface SettingsMultiLabelView : _AudioQueueAllocateBuffer
{
    float topEdge_;
    float bottomEdge_;
}

- (void)setBottomEdge:(float)fp8;
- (float)bottomEdge;
- (void)setTopEdge:(float)fp8;
- (float)topEdge;
- (float)label:(id)fp8 heightForWidth:(float)fp12;
- (void)layoutSubviews;
- (float)heightForWidth:(float)fp8;
- (id)init;

@end

