/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class UILabel;

@interface ShareToTableViewController : _AudioQueueAllocateBuffer
{
    UILabel *headerLabel_;
    struct scoped_nsobject<NSArray> services_;
    id <ShareToTableDelegate> delegate_;
    struct ObjCPropertyReleaser propertyReleaser_ShareToTableViewController_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setHeaderLabel:(id)fp8;
- (id)headerLabel;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (void)setHeaderText:(id)fp8;
- (id)initWithStyle:(int)fp8;
- (id)initWithCoder:(id)fp8;
- (void)setServices:(id)fp8;
- (float)maxHeight;

@end

