/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSString;

@interface ShareToService : _AudioQueueAllocateBuffer
{
    NSString *name_;
    NSString *iconFile_;
    BOOL valid_;
    struct ObjCPropertyReleaser propertyReleaser_ShareToService_;
}

- (void)setValid:(BOOL)fp8;
- (BOOL)isValid;
- (void)setIconFile:(id)fp8;
- (id)iconFile;
- (void)setName:(id)fp8;
- (id)name;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)shareURL:(id)fp8 withPattern:(id)fp12;
- (void)shareURL:(id)fp8 title:(id)fp12;
- (id)icon;
- (id)initWithName:(id)fp8 iconFile:(id)fp12;
- (BOOL)shouldBeEnabled;

@end

