/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ChromeToDeviceJob.h"

@class NSURL;

@interface SnapshotJob : ChromeToDeviceJob
{
    NSURL *originalUrl_;
    struct ObjCPropertyReleaser propertyReleaser_SnapshotJob_;
}

- (void)setOriginalUrl:(id)fp8;
- (id)originalUrl;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithId:(id)fp8 title:(id)fp12 originalUrl:(id)fp16 status:(int)fp20 tab:(id)fp24;

@end

