/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "GIPGoogleDialogDelegate-Protocol.h"
#import "GIPSpeechWindowDelegate-Protocol.h"

@interface SpeechRecognitionBubbleBridge : _AudioQueueAllocateBuffer <GIPGoogleDialogDelegate, GIPSpeechWindowDelegate>
{
    float inputLevel_;
    struct scoped_nsobject<GIPSpeechWindowController> speechWindowController_;
    struct Delegate *speechRecognitionBubbleDelegate_;
}

- (void)setInputLevel:(float)fp8;
- (float)inputLevel;
- (id).cxx_construct;
- (void).cxx_destruct;
- (float)audioInputLevel;
- (BOOL)isLiveWaveformEnabled;
- (void)dialog:(id)fp8 dialogDidPress:(id)fp12;
- (void)dialog:(id)fp8 defaultButtonDidPress:(id)fp12;
- (void)dialog:(id)fp8 rightButtonDidPress:(id)fp12;
- (void)dialog:(id)fp8 leftButtonDidPress:(id)fp12;
- (id)speechWindowController;
- (id)initWithSpeechRecognitionBubbleDelegate:(struct Delegate *)fp8;

@end

