/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface SpeechInputLocales : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NSArray> supportedLocales_;
    struct scoped_nsobject<NSMutableDictionary> localesByLanguages_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (unsigned int)count;
- (id)codeAtIndex:(unsigned int)fp8;
- (id)languageNameFromCode:(id)fp8;
- (void)loadLocalesPlist;
- (id)getFallbackSupportedLocales;
- (id)defaultLocale;
- (id)defaultLocaleForLanguage:(id)fp8;
- (id)init;

@end

