/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface SSLCarrier : _AudioQueueAllocateBuffer
{
    struct scoped_refptr<RequestTracker> tracker_;
    struct SSLInfo sslInfo_;
    struct GURL url_;
    struct scoped_ptr<SSLErrorInfo> error_;
    struct SSLStatus status_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)description;
- (void)buildSSLStatus;
- (void)errorCallback:(BOOL)fp8;
- (const struct SSLErrorInfo *)sslError;
- (const struct SSLStatus *)sslStatus;
- (const struct SSLInfo *)sslInfo;
- (const struct GURL *)url;
- (id)initWithTracker:(struct RequestTracker *)fp8 counts:(const struct TrackerCounts *)fp12;

@end

