/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "CardSetObserver-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class CardSet, UIPanGestureRecognizer, UIScrollView, UIView;

@interface StackViewController : _AudioQueueAllocateBuffer <CardSetObserver, UIGestureRecognizerDelegate, UIScrollViewDelegate>
{
    UIScrollView *scrollView_;
    UIView *backgroundView_;
    struct scoped_nsobject<CardSet> mainCardSet_;
    struct scoped_nsobject<CardSet> otrCardSet_;
    CardSet *activeCardSet_;
    id <StackViewControllerDelegate> delegate_;
    id <StackViewControllerTestDelegate> testDelegate_;
    struct scoped_nsobject<StackViewToolbarController> toolbarController_;
    struct CGSize initialCardSize_;
    int lastInterfaceOrientation_;
    struct scoped_nsobject<UITapGestureRecognizer> modeSwitchRecognizer_;
    struct scoped_nsobject<UIGestureRecognizer> pinchRecognizer_;
    struct scoped_nsobject<UIGestureRecognizer> swipeGestureRecognizer_;
    struct scoped_nsobject<UIGestureRecognizer> swipeDismissesCardRecognizer_;
    struct scoped_nsobject<GestureStateTracker> gestureStateTracker_;
    BOOL ignoreScrollCallbacks_;
    UIPanGestureRecognizer *scrollGestureRecognizer_;
    struct scoped_nsobject<StackCard> reverseDismissCard_;
    BOOL isBeingDismissed_;
    BOOL isActive_;
    BOOL receivedMemoryWarningInSession_;
}

- (void)setTestDelegate:(id)fp8;
- (id)testDelegate;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)scrollViewDidEndDecelerating:(id)fp8;
- (void)scrollViewDidEndDragging:(id)fp8 willDecelerate:(BOOL)fp12;
- (void)scrollViewDidScroll:(id)fp8;
- (void)adjustMaximumOverextensionAmount:(BOOL)fp8;
- (void)killScrollDeceleration;
- (void)animateOverextensionEliminationWithCompletion:(id)fp(null);
- (void)pinchEnded;
- (void)scrollEnded;
- (BOOL)shouldEndScroll;
- (void)alignDisplayViewsToViewport;
- (void)recenterScrollViewIfNecessary;
- (void)cardSetRecreatedCards:(id)fp8;
- (void)cardSet:(id)fp8 displayedCard:(id)fp12;
- (void)cardSet:(id)fp8 removedCard:(id)fp12 atIndex:(unsigned int)fp16;
- (void)cardSet:(id)fp8 addedCard:(id)fp12;
- (void)allModelTabsHaveClosed:(id)fp8;
- (void)showToolsMenuPopup;
- (void)chromeExecuteCommand:(id)fp8;
- (id)cardForView:(id)fp8;
- (void)swipeCard:(id)fp8;
- (void)swipeDeck:(id)fp8;
- (BOOL)swipeShouldTriggerAction:(float)fp8;
- (float)distanceForSwipeToTriggerAction;
- (void)determineSwipeType:(id)fp8;
- (void)handlePanFrom:(id)fp8;
- (void)handleTapFrom:(id)fp8;
- (void)handlePinchFrom:(id)fp8;
- (void)handleLongPressFrom:(id)fp8;
- (void)closeTab:(id)fp8;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (id)displayTransitionToolbarView;
- (id)dismissWithNewTabAnimation:(id)fp8;
- (id)dismissWithNewTabAnimationInMainModel:(id)fp8;
- (void)setCardsZoomedToFillScreen:(BOOL)fp8;
- (void)setViewTransitionPositions;
- (void)dismissWithSelectedTabAnimation;
- (void)showWithSelectedTabAnimation;
- (unsigned int)startIndexOfInitialFanoutForCardSet:(id)fp8;
- (unsigned int)indexOfCardAtPoint:(struct CGPoint)fp8;
- (struct CGRect)inactiveDeckRegion;
- (struct CGSize)sizeForScrollLength:(float)fp8 breadth:(float)fp12;
- (float)scrollBreadth:(struct CGSize)fp8;
- (float)scrollLength:(struct CGSize)fp8;
- (struct CGPoint)scrollOffsetPointWithAmount:(float)fp8;
- (float)scrollOffsetAmountForPoint:(struct CGPoint)fp8;
- (float)cardContentScale;
- (struct CGSize)cardSizeForBreadth:(float)fp8;
- (struct CGSize)cardSize;
- (void)updateToolbarAppearanceWithAnimation:(BOOL)fp8;
- (void)displayMainCardSetOnly;
- (void)displayActiveCardSet;
- (void)setActiveCardSet:(id)fp8;
- (id)inactiveCardSet;
- (BOOL)isCurrentSetIncognito;
- (BOOL)bothDecksShouldBeDisplayed;
- (float)shiftOffscreenAmountForCardSet:(id)fp8;
- (void)updateDeckAxisPositionForCardSet:(id)fp8 withShiftAmount:(float)fp12;
- (void)updateDeckAxisPositionsWithShiftAmount:(float)fp8;
- (void)updateDeckAxisPositions;
- (void)animateActiveSetCardTabsToOpacity:(float)fp8 withDuration:(float)fp12 completion:(id)fp(null);
- (void)updateCardSizesWithAnimation:(BOOL)fp8;
- (void)updateDeckOrientationWithAnimation:(BOOL)fp8;
- (void)setInitialCardSizing;
- (void)activeCardCountChanged;
- (void)removeAllCardsFromSet:(id)fp8;
- (void)animateOutCardView:(id)fp8 delay:(double)fp12 clockwise:(BOOL)fp20 completion:(id)fp(null);
- (void)preloadNextCardView;
- (void)preloadCardViewsAsynchronously;
- (void)cleanUpViewsAndNotifications;
- (void)prepareForDismissal;
- (void)deregisterForNotifications;
- (void)registerForNotifications;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidUnload;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)refreshCardDisplayWithAnimation:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)prepareForDisplay;
- (void)setUpDisplayViews;
- (id)scrollViewScrollGestureRecognizer;
- (void)updateScrollViewContentSize;
- (void)viewportSizeWasChanged;
- (void)clearInternalState;
- (void)restoreInternalStateWithMainTabModel:(id)fp8 otrTabModel:(id)fp12 activeTabModel:(id)fp16;
- (void)setUpWithMainCardSet:(id)fp8 otrCardSet:(id)fp12 activeCardSet:(id)fp16;
- (id)initWithMainTabModel:(id)fp8 otrTabModel:(id)fp12 activeTabModel:(id)fp16;
- (id)initWithMainCardSet:(id)fp8 otrCardSet:(id)fp12 activeCardSet:(id)fp16;

@end

