/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ToolbarController.h"

@class UIButton, UIView;

@interface StackViewToolbarController : ToolbarController
{
    UIView *stackViewToolbar_;
    UIButton *buttonNewTab_;
    struct ObjCPropertyReleaser propertyReleaser_StackViewToolbarController_;
}

- (void)setButtonNewTab:(id)fp8;
- (id)buttonNewTab;
- (void)setStackViewToolbar:(id)fp8;
- (id)stackViewToolbar;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setNewTabButtonIsIncognito:(BOOL)fp8;
- (void)recordUserMetrics:(id)fp8;
- (id)init;

@end

