/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "StaticHtmlViewController.h"

#import "NativeContent-Protocol.h"

@interface StaticHtmlNativeContent : StaticHtmlViewController <NativeContent>
{
    struct scoped_nsobject<NSURL> url_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)view;
- (id)url;
- (id)initWithLoader:(id)fp8 url:(id)fp12 generator:(id)fp16;
- (id)initWithLoader:(id)fp8 profile:(struct Profile *)fp12 url:(id)fp16 resource:(id)fp20;

@end

