/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "UIWebViewDelegate-Protocol.h"

@interface StaticHtmlViewController : _AudioQueueAllocateBuffer <UIWebViewDelegate>
{
    id <UrlLoader> loader_;
    struct scoped_nsobject<UIWebView> view_;
    struct scoped_nsobject<NSURL> referrer_;
    struct scoped_nsobject<NSURL> resourceUrl_;
    struct scoped_nsobject<NSString> resource_;
    struct Profile *profile_;
    struct scoped_nsobject<id> generator_;
    id <TitleChangedDelegate> titleChangedDelegate_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)newView;
- (id)resourceURL;
- (void)webViewDidFinishLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)setTitleChangedDelegate:(id)fp8;
- (void)reload;
- (id)title;
- (BOOL)isViewAlive;
- (void)handleLowMemory;
- (id)webView;
- (void)setLoader:(id)fp8 referrer:(id)fp12;
- (void)dealloc;
- (id)initWithGenerator:(id)fp8;
- (id)initWithResource:(id)fp8 profile:(struct Profile *)fp12;

@end

