/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NIAttributedLabelDelegate-Protocol.h"

@interface SyncErrorController : _AudioQueueAllocateBuffer <NIAttributedLabelDelegate>
{
    struct Profile *profile_;
    int syncServiceState_;
    struct scoped_nsobject<NSString> customMessage_;
    struct scoped_nsobject<UILabel> footerLabel_;
    struct set<SyncSetupService::SyncServiceState, std::less<SyncSetupService::SyncServiceState>, std::allocator<SyncSetupService::SyncServiceState>> monitoredSyncStates_;
    BOOL needsViewUpdate_;
    struct scoped_nsobject<SettingsMultiLabelView> view_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)attributedLabel:(id)fp8 didSelectLink:(id)fp12 atPoint:(struct CGPoint)fp16;
- (void)initFooterLabel:(id)fp8 title:(id)fp12;
- (void)initErrorLabel:(id)fp8 title:(id)fp12;
- (void)addLinkLabelWithTitle:(id)fp8 url:(id)fp12;
- (void)addLabelWithTitle:(id)fp8;
- (float)heightForWidth:(float)fp8;
- (void)updateView;
- (void)initView;
- (BOOL)shouldUpdateView;
- (id)view;
- (void)addIgnoreSyncState:(int)fp8;
- (void)addMonitorSyncState:(int)fp8;
- (void)setFooterMessage:(id)fp8;
- (void)setCustomMessage:(id)fp8;
- (id)initWithProfile:(struct Profile *)fp8;
- (id)initWithNoMonitoredSyncStateAndProfile:(struct Profile *)fp8;

@end

