/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SyncEncryptionPassphraseTableViewController.h"

@interface SyncCreatePassphraseTableViewController : SyncEncryptionPassphraseTableViewController
{
    struct scoped_nsobject<UITextField> confirmPassphrase_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)textFieldsHaveInput;
- (void)signInPressed;
- (void)nextTextField:(id)fp8;
- (void)editingChanged:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (BOOL)forDecryption;
- (void)viewDidUnload;
- (void)viewDidLoad;

@end

