/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface SyncNotificationBridge : _AudioQueueAllocateBuffer
{
    struct Core *delegate_;
}

- (void)dealloc;
- (void)ApplicationDidBecomeActive;
- (id)initWithDelegate:(struct Core *)fp8;

@end

