/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface SyncAdvancedSettingsTableViewController : _AudioQueueAllocateBuffer
{
    struct Profile *profile_;
    struct SyncSetupService *syncSetupService_;
    struct scoped_nsobject<UISwitch> syncEverythingSwitch_;
    struct scoped_nsobject<NSMutableArray> dataTypeSwitches_;
    struct scoped_nsobject<SyncErrorController> syncErrorController_;
    struct scoped_nsobject<SettingsLinkController> dashboardController_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (BOOL)isEncryptionSection:(int)fp8;
- (void)updateDataTypeSwitch:(int)fp8;
- (void)dataTypeSwitchChanged:(id)fp8;
- (void)syncEverythingSwitchChanged:(id)fp8;
- (id)switchForDataType:(int)fp8;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (void)prepareEncryptionCell:(id)fp8;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (float)tableView:(id)fp8 heightForFooterInSection:(int)fp12;
- (id)tableView:(id)fp8 viewForFooterInSection:(int)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (id)initWithProfile:(struct Profile *)fp8;

@end

