/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SettingsMultiLabelView.h"

@interface TableViewErrorFooter : SettingsMultiLabelView
{
    struct scoped_nsobject<UILabel> label_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setErrorMessage:(id)fp8;
- (id)errorMessage;
- (id)initWithMessage:(id)fp8;

@end

