/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "NSFastEnumeration-Protocol.h"

@class Tab;

@interface TabModel : _AudioQueueAllocateBuffer <NSFastEnumeration>
{
    struct scoped_ptr<TabRestoreServiceDelegateIOS> tabRestoreDelegate_;
    struct scoped_nsobject<NSMutableArray> tabs_;
    struct scoped_nsobject<TabModelOrderController> orderController_;
    struct scoped_ptr<TabModelSyncedWindowDelegate> syncedWindowDelegate_;
    Tab *currentTab_;
    Tab *nextTab_;
    struct Profile *profile_;
    int openedTabCounter_;
    int closedTabCounter_;
    int newTabCounter_;
    BOOL suspended_;
    struct scoped_nsobject<SessionServiceIOS> sessionService_;
    struct vector<id, std::allocator<id>> observers_;
}

+ (void)handleLowMemory:(unsigned int)fp8 tabs:(id)fp12;
- (struct Profile *)profile;
- (void)setNextTab:(id)fp8;
- (id)nextTab;
- (id)currentTab;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)recordSessionMetrics;
- (void)resetSessionMetrics;
- (BOOL)isOffTheRecord;
- (void)resumeWebUsage;
- (void)suspendWebUsage;
- (struct TabModelSyncedWindowDelegate *)syncedWindowDelegate;
- (void)notifyTabProgressChanged:(id)fp8;
- (void)notifyTabChanged:(id)fp8;
- (id)nextTabOpenedBy:(id)fp8 after:(id)fp12;
- (id)openerOfTab:(id)fp8;
- (id)lastTabOpenedBy:(id)fp8;
- (id)firstTabOpenedBy:(id)fp8;
- (unsigned int)countByEnumeratingWithState:(CDAnonymousStruct1 *)fp8 objects:(id *)fp12 count:(unsigned int)fp16;
- (void)closeAllTabs;
- (void)stopTabFromWindowName:(id)fp8;
- (void)closeTabFromWindowName:(id)fp8;
- (id)tabForWindowName:(id)fp8;
- (void)closeTabAtIndex:(unsigned int)fp8;
- (void)closeTab:(id)fp8;
- (void)tabClosed:(id)fp8;
- (void)replaceTab:(id)fp8 withTab:(id)fp12;
- (void)moveTab:(id)fp8 toIndex:(unsigned int)fp12;
- (void)changeSelectedTabFrom:(id)fp8 to:(id)fp12 persistState:(BOOL)fp16;
- (void)setCurrentTab:(id)fp8;
- (void)updateSnapshotCache:(id)fp8;
- (id)tabFromWebController:(id)fp8;
- (unsigned int)indexOfTab:(id)fp8;
- (id)insertTabWithSessionController:(id)fp8 atIndex:(unsigned int)fp12;
- (id)insertURL:(id)fp8 referrer:(id)fp12 windowName:(id)fp16 opener:(id)fp20 atIndex:(unsigned int)fp24;
- (void)insertTab:(id)fp8 atIndex:(unsigned int)fp12;
- (id)appendURL:(id)fp8 referrer:(id)fp12 windowName:(id)fp16;
- (void)addOrUpdateTabWithURL:(id)fp8 referrer:(id)fp12 windowName:(id)fp16 transition:(int)fp20 index:(unsigned int)fp24 inBackground:(BOOL)fp28 opener:(id)fp32;
- (id)addTabWithURL:(id)fp8 referrer:(id)fp12 windowName:(id)fp16 transition:(int)fp20 index:(unsigned int)fp24 inBackground:(BOOL)fp28 opener:(id)fp32;
- (unsigned int)count;
- (BOOL)isEmpty;
- (id)urlAtIndex:(unsigned int)fp8;
- (id)tabAtIndex:(unsigned int)fp8;
- (void)removeObserver:(id)fp8;
- (void)addObserver:(id)fp8;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)saveSession:(BOOL)fp8;
- (id)windowForSavingSession;
- (void)lowMemoryWarning:(id)fp8;
- (void)postNotificationName:(id)fp8 withTab:(id)fp12;
- (BOOL)restoreSessionWindow:(id)fp8;
- (void)dealloc;
- (id)initWithSessionWindow:(id)fp8 sessionService:(id)fp12 profile:(struct Profile *)fp16;

@end

