/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "TabModelObserver-Protocol.h"
#import "TabStripViewLayoutDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSTimer, TabModel, TabStripView, UIButton, UIView;

@interface TabStripController : _AudioQueueAllocateBuffer <TabModelObserver, TabStripViewLayoutDelegate, UIGestureRecognizerDelegate, UIScrollViewDelegate>
{
    TabModel *tabModel_;
    UIView *view_;
    TabStripView *tabStripView_;
    UIButton *buttonNewTab_;
    UIButton *modeToggleButton_;
    int style_;
    struct scoped_nsobject<TabSpinnerImageProvider> spinnerProvider_;
    struct scoped_nsobject<NSMutableArray> tabArray_;
    struct scoped_nsobject<NSMutableSet> closingTabs_;
    struct TargetFrameCache targetFrames_;
    BOOL animateLayout_;
    float currentTabWidth_;
    struct scoped_nsobject<UIView> dimmingView_;
    BOOL highlightsSelectedTab_;
    BOOL isReordering_;
    struct scoped_nsobject<TabView> draggedTab_;
    struct CGPoint lastDragLocation_;
    NSTimer *autoscrollTimer_;
    float autoscrollDistance_;
    unsigned int placeholderGapModelIndex_;
    BOOL hasModeToggleSwitch_;
    struct ObjCPropertyReleaser propertyReleaser_TabStripController_;
}

- (id)modeToggleButton;
- (BOOL)hasModeToggleSwitch;
- (BOOL)highlightsSelectedTab;
- (void)setButtonNewTab:(id)fp8;
- (id)buttonNewTab;
- (void)setTabStripView:(id)fp8;
- (id)tabStripView;
- (void)setView:(id)fp8;
- (id)view;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)setNeedsLayoutWithAnimation;
- (void)layoutTabStripSubviews;
- (struct CGRect)calculateVisibleFrameForFrame:(struct CGRect)fp8 whenUnderFrame:(struct CGRect)fp24;
- (struct CGRect)scrollViewFrameForTab:(id)fp8;
- (void)updateContentSizeAndRepositionViews;
- (void)removeModeToggleButton;
- (void)installModeToggleButton;
- (void)installIncognitoIcon;
- (void)tabModel:(id)fp8 replacedTab:(id)fp12 withTab:(id)fp16 atIndex:(unsigned int)fp20;
- (void)tabModel:(id)fp8 changedTab:(id)fp12;
- (void)tabModel:(id)fp8 activeTabChanged:(id)fp12 previousTab:(id)fp16 atIndex:(unsigned int)fp20;
- (void)tabModel:(id)fp8 movedTab:(id)fp12 fromIndex:(unsigned int)fp16 toIndex:(unsigned int)fp20;
- (void)tabModel:(id)fp8 removedTab:(id)fp12 atIndex:(unsigned int)fp16;
- (void)tabModel:(id)fp8 insertedTab:(id)fp12 atIndex:(unsigned int)fp16 inForeground:(BOOL)fp20;
- (void)constrainAutoscrollDistance;
- (void)computeAutoscrollDistanceForTabView:(id)fp8;
- (void)autoscrollTimerFired:(id)fp8;
- (void)removeAutoscrollTimer;
- (void)installAutoscrollTimerIfNeeded;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (BOOL)isReorderingTabs;
- (void)resetDragState;
- (void)cancelDrag:(id)fp8;
- (void)endDrag:(id)fp8;
- (void)continueDrag:(id)fp8;
- (void)beginDrag:(id)fp8;
- (unsigned int)modelIndexForTabView:(id)fp8;
- (unsigned int)modelIndexForIndex:(unsigned int)fp8;
- (unsigned int)indexForModelIndex:(unsigned int)fp8;
- (void)handleLongPress:(id)fp8;
- (void)closeTab:(id)fp8;
- (void)tabTapped:(id)fp8;
- (void)recordUserMetrics:(id)fp8;
- (void)removeDimmingViewWithAnimation:(BOOL)fp8;
- (void)installDimmingViewWithAnimation:(BOOL)fp8;
- (void)setHighlightsSelectedTab:(BOOL)fp8;
- (id)tabViewForTab:(id)fp8;
- (void)setHasModeToggleSwitch:(BOOL)fp8;
- (void)initializeTabArrayFromTabModel;
- (void)dealloc;
- (id)initWithTabModel:(id)fp8 style:(int)fp12;

@end

