/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface TabSpinnerImageProvider : _AudioQueueAllocateBuffer
{
    struct scoped_nsobject<NSMutableArray> spinnerImages_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (id)spinnerImages;

@end

