/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface TabStripView : _AudioQueueAllocateBuffer
{
    id <TabStripViewLayoutDelegate> layoutDelegate_;
}

- (void)setLayoutDelegate:(id)fp8;
- (id)layoutDelegate;
- (void)layoutSubviews;
- (BOOL)touchesShouldCancelInContentView:(id)fp8;

@end

