/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface ThumbnailHelper : _AudioQueueAllocateBuffer
{
    struct Profile *profile_;
}

- (BOOL)updateThumbnailForTabIfNecessary:(id)fp8;
- (id)generateThumbnail:(id)fp8 score:(struct ThumbnailScore *)fp12;
- (struct CGSize)thumbnailSize;
- (id)initWithProfile:(struct Profile *)fp8;

@end

