/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class UIImage;

@interface ToolbarBackgroundView : _AudioQueueAllocateBuffer
{
    UIImage *image_;
}

- (void)setImage:(id)fp8;
- (id)image;
- (void)drawRect:(struct CGRect)fp8;

@end

