/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "ToolsPopupTableDelegate-Protocol.h"

@class ToolsPopupTableViewController, ToolsPopupView, UIButton, UITableView, UIView;

@interface ToolsPopupController : _AudioQueueAllocateBuffer <ToolsPopupTableDelegate>
{
    UIView *containerView_;
    ToolsPopupView *toolsContainer_;
    ToolsPopupTableViewController *toolsTableViewController_;
    UITableView *toolsTableView_;
    UIView *toolsTableViewContainer_;
    UIButton *reloadButton_;
    UIButton *stopButton_;
    UIButton *bookmarkAdd_;
    UIButton *bookmarkEdit_;
    UIButton *backgroundButton_;
    BOOL isCurrentPageBookmarked_;
    id <ToolsPopupDelegate> delegate_;
    struct ObjCPropertyReleaser propertyReleaser_ToolsPopupController_;
}

- (BOOL)isCurrentPageBookmarked;
- (void)setBookmarkEdit:(id)fp8;
- (id)bookmarkEdit;
- (void)setBookmarkAdd:(id)fp8;
- (id)bookmarkAdd;
- (void)setStopButton:(id)fp8;
- (id)stopButton;
- (void)setReloadButton:(id)fp8;
- (id)reloadButton;
- (void)setToolsTableViewContainer:(id)fp8;
- (id)toolsTableViewContainer;
- (void)setToolsTableViewController:(id)fp8;
- (id)toolsTableViewController;
- (void)setToolsTableView:(id)fp8;
- (id)toolsTableView;
- (void)setToolsContainer:(id)fp8;
- (id)toolsContainer;
- (void)setContainerView:(id)fp8;
- (id)containerView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setBackgroundButton:(id)fp8;
- (id)backgroundButton;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)commandWasSelected:(int)fp8;
- (void)setIsTabLoading:(BOOL)fp8;
- (void)setCanShowShareMenu:(BOOL)fp8;
- (void)setCanShowFindBar:(BOOL)fp8;
- (void)setCanUseDesktopUserAgent:(BOOL)fp8;
- (void)setIsCurrentPageBookmarked:(BOOL)fp8;
- (void)tappedBehindPopup:(id)fp8;
- (id)view;
- (void)dealloc;
- (void)highlightArrow:(id)fp8;
- (id)initWithOrigin:(struct CGPoint)fp8 parentView:(id)fp16 options:(unsigned int)fp20;

@end

