/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface ToolsPopupView : _AudioQueueAllocateBuffer
{
    struct CGPoint arrowPosition_;
    struct CGPath *path_;
    struct CGPath *innerPath_;
    BOOL highlighted_;
}

- (BOOL)highlighted;
- (struct CGPoint)arrowPosition;
- (id).cxx_construct;
- (struct CGPath *)newPathForRect:(struct CGRect)fp8 withArrow:(BOOL)fp24;
- (struct CGPath *)borderPath;
- (struct CGPath *)innerBorderPath;
- (struct CGRect)rectangleBounds;
- (void)drawRect:(struct CGRect)fp8;
- (void)setHighlighted:(BOOL)fp8;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)setArrowPosition:(struct CGPoint)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)dealloc;

@end

