/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class NSString, UITableViewCell;

@interface ToolsPopupMenuItem : _AudioQueueAllocateBuffer
{
    NSString *title_;
    int titleId_;
    NSString *uiAutomationLabel_;
    UITableViewCell *tableViewCell_;
    BOOL active_;
    struct ObjCPropertyReleaser propertyReleaser_ToolsPopupMenuItem_;
    int tag_;
}

+ (id)menuItemWithtableViewCell:(id)fp8;
+ (id)menuItem:(int)fp8 title:(id)fp12 uiAutomationLabel:(id)fp16 command:(int)fp20;
- (void)setActive:(BOOL)fp8;
- (BOOL)active;
- (void)setTag:(int)fp8;
- (int)tag;
- (void)setTableViewCell:(id)fp8;
- (id)tableViewCell;
- (void)setUiAutomationLabel:(id)fp8;
- (id)uiAutomationLabel;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setTitleId:(int)fp8;
- (int)titleId;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)customizeCell:(id)fp8;
- (id)init;

@end

