/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "SyncViewControllerFactory-Protocol.h"

@interface TosSyncViewControllerFactory : _AudioQueueAllocateBuffer <SyncViewControllerFactory>
{
    id <FirstRunMetricsDelegate> metricsDelegate_;
}

- (id)newActivityIndicatorView;
- (struct UIViewController *)newSyncAspController:(struct ChromeLoginControllerDelegate *)fp8;
- (struct UIViewController *)newSyncCaptchaController:(struct ChromeLoginControllerDelegate *)fp8;
- (struct UIViewController *)newSyncLoginController:(struct ChromeLoginControllerDelegate *)fp8;
- (id)initWithMetricsDelegate:(id)fp8;

@end

