/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "UIKeyInput-Protocol.h"

@protocol UITextInput <UIKeyInput>
- (id)tokenizer;
- (void)setInputDelegate:(id)fp8;
- (id)inputDelegate;
- (id)endOfDocument;
- (id)beginningOfDocument;
- (void)setMarkedTextStyle:(id)fp8;
- (id)markedTextStyle;
- (id)markedTextRange;
- (void)setSelectedTextRange:(id)fp8;
- (id)selectedTextRange;
- (id)characterRangeAtPoint:(struct CGPoint)fp8;
- (id)closestPositionToPoint:(struct CGPoint)fp8 withinRange:(id)fp16;
- (id)closestPositionToPoint:(struct CGPoint)fp8;
- (struct CGRect)caretRectForPosition:(id)fp8;
- (struct CGRect)firstRectForRange:(id)fp8;
- (void)setBaseWritingDirection:(int)fp8 forRange:(id)fp12;
- (int)baseWritingDirectionForPosition:(id)fp8 inDirection:(int)fp12;
- (id)characterRangeByExtendingPosition:(id)fp8 inDirection:(int)fp12;
- (id)positionWithinRange:(id)fp8 farthestInDirection:(int)fp12;
- (int)offsetFromPosition:(id)fp8 toPosition:(id)fp12;
- (int)comparePosition:(id)fp8 toPosition:(id)fp12;
- (id)positionFromPosition:(id)fp8 inDirection:(int)fp12 offset:(int)fp16;
- (id)positionFromPosition:(id)fp8 offset:(int)fp12;
- (id)textRangeFromPosition:(id)fp8 toPosition:(id)fp12;
- (void)unmarkText;
- (void)setMarkedText:(id)fp8 selectedRange:(struct _NSRange)fp12;
- (void)replaceRange:(id)fp8 withText:(id)fp12;
- (id)textInRange:(id)fp8;
@end

