/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@interface UpgradeCenter : _AudioQueueAllocateBuffer
{
    BOOL upgradeInfoBarIsVisible_;
    struct scoped_nsobject<NSMutableDictionary> upgradeInfoBarDelegates_;
    struct set<id<UpgradeCenterClientProtocol>, std::less<id<UpgradeCenterClientProtocol>>, std::allocator<id<UpgradeCenterClientProtocol>>> clients_;
    // Error parsing type: {scoped_ptr<<anonymous>::UpgradeNotificationObserver>="ptr_"^{UpgradeNotificationObserver}}, name: upgradeObserver_
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)sharedInstance;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)resetForTests;
- (void)upgradeNotificationDidOccur:(const CDAnonymousStruct2 *)fp8;
- (void)hideUpgradeInfoBars;
- (void)showUpgradeInfoBars;
- (void)dismissedInfoBar:(id)fp8 performUpgrade:(BOOL)fp12;
- (void)tabWillClose:(id)fp8;
- (void)addInfoBarToHelper:(struct InfoBarTabHelper *)fp8 forTabId:(id)fp12;
- (void)unregisterClient:(id)fp8;
- (void)registerClient:(id)fp8;
- (void)applicationWillEnterForeground:(id)fp8;
- (BOOL)isCurrentVersionObsolete;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)autorelease;
- (oneway void)release;
- (unsigned int)retainCount;
- (id)retain;

@end

