/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol UrlLoader
- (void)loadSessionTab:(const struct SessionTab *)fp8;
- (void)webPageOrderedOpen:(id)fp8 referrer:(id)fp12 windowName:(id)fp16 inIncognito:(BOOL)fp20 inBackground:(BOOL)fp24 appendTo:(int)fp28;
- (void)webPageOrderedOpen:(id)fp8 referrer:(id)fp12 windowName:(id)fp16 inBackground:(BOOL)fp20 appendTo:(int)fp24;
- (void)loadURL:(id)fp8 referrer:(id)fp12 transition:(int)fp16 rendererInitiated:(BOOL)fp20;
@end

