/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "UserFeedbackActionDelegate-Protocol.h"

@interface UserFeedbackController : _AudioQueueAllocateBuffer <UserFeedbackActionDelegate>
{
    struct scoped_nsobject<FeedbackTableViewController> feedbackTableViewController_;
    struct scoped_nsobject<FeedbackController> feedbackController_;
    struct scoped_nsobject<NSString> account_;
    id <UserFeedbackDataSource> dataSource_;
    id completionTarget_;
    SEL completionAction_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)cancel:(id)fp8;
- (void)submitFeedback:(id)fp8;
- (id)syncedUserName;
- (id)screenshot;
- (id)url;
- (BOOL)isIncognito;
- (id)viewController;
- (void)dealloc;
- (id)initWithController:(id)fp8 dataSource:(id)fp12 completionTarget:(id)fp16 completionAction:(SEL)fp20;

@end

