/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

@class SpeechInputLocales;

@interface VoicesearchTableViewController : _AudioQueueAllocateBuffer
{
    int checkedRow_;
    struct PrefService *prefs_;
    // Error parsing type: {PrefMember<std::basic_string<char> >="_vptr$NotificationObserver"^^?"pref_name_"{basic_string<char, std::char_traits<char>, std::allocator<char> >="_M_dataplus"{_Alloc_hider="_M_p"*}}"observer_"^{NotificationObserver}"prefs_"^{PrefService}"setting_value_"B"internal_"{scoped_refptr<PrefMember<std::basic_string<char> >::Internal>="ptr_"^{Internal}}}, name: selectedLanguage_
    SpeechInputLocales *speechInputLocales_;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)tableView:(id)fp8 didSelectRowAtIndexPath:(id)fp12;
- (id)tableView:(id)fp8 cellForRowAtIndexPath:(id)fp12;
- (int)tableView:(id)fp8 numberOfRowsInSection:(int)fp12;
- (int)numberOfSectionsInTableView:(id)fp8;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (id)initWithPrefs:(struct PrefService *)fp8 supportedSpeechInputLocales:(id)fp12;

@end

