/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_AudioQueueAllocateBuffer.h"

#import "TouchTrackingDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class NSTimer;

@interface WebController : _AudioQueueAllocateBuffer <TouchTrackingDelegate, UIWebViewDelegate, UIActionSheetDelegate, UIGestureRecognizerDelegate>
{
    id <WebDelegate> delegate_;
    id <NativeContentProvider> nativeProvider_;
    id <ContextMenuProvider> contextMenuProvider_;
    id <SwipeRecognizerProvider> swipeRecognizerProvider_;
    struct scoped_nsobject<UIView> contentView_;
    struct scoped_nsobject<Interstitial> interstitial_;
    struct scoped_nsobject<UIWebView> contentAsWebView_;
    struct scoped_nsobject<NSString> windowId_;
    struct scoped_nsprotocol<id<NativeContent>> nativeController_;
    BOOL isBeingDestroyed_;
    struct scoped_nsobject<NSString> chromeObject_;
    struct scoped_nsobject<ContextMenuController> contextMenuController_;
    struct scoped_nsobject<PasswordController> passwordController_;
    struct Profile *profile_;
    BOOL userInteractionRegistered_;
    struct scoped_nsobject<SnapshotManager> snapshotManager_;
    struct scoped_nsobject<NSURL> urlOnWillStartLoading_;
    struct scoped_nsobject<NSURL> urlOnStartLoading_;
    struct scoped_nsobject<NSString> lastDetectedTitle_;
    NSTimer *continuousCheckTimer_;
    int loadPhase_;
    struct scoped_nsobject<NSMutableArray> pendingLoadCompleteActions_;
    BOOL isBrowsingSuspended_;
    BOOL inJavaScriptContext_;
    BOOL useSnapshotOverlay_;
    struct scoped_nsobject<UIImageView> snapshotOverlayView_;
    struct scoped_nsobject<FindInPageModel> findInPageModel_;
    struct scoped_nsobject<TouchTrackingRecognizer> touchTrackingRecognizer_;
    BOOL clickInProgress_;
    double lastClickTimeInSeconds_;
    double lastTransferTimeInSeconds_;
    struct scoped_nsobject<NSURL> defaultURL_;
    struct scoped_ptr<BlockedPopupHandler> popupHandler_;
    BOOL overlayPreviewMode_;
    BOOL useGreyImageCache_;
    BOOL setSuppressDialogsLater_;
    struct scoped_nsobject<NSMutableDictionary> externalRequest_;
    struct scoped_nsobject<ExternalAppLauncher> externalAppLauncher_;
    BOOL spoofableRequest_;
    BOOL ignoreSnapshotOverlay_;
}

+ (void)setPriorityRecognizer:(id)fp8 inView:(id)fp12 containingDescription:(id)fp16;
+ (void)requireGestureRecognizerToFail:(id)fp8 inView:(id)fp12 containingDescription:(id)fp16;
+ (id)defaultSnapshotImage;
- (void)setUseGreyImageCache:(BOOL)fp8;
- (BOOL)useGreyImageCache;
- (int)loadPhase;
- (void)setSwipeRecognizerProvider:(id)fp8;
- (id)swipeRecognizerProvider;
- (void)setUseSnapshotOverlay:(BOOL)fp8;
- (BOOL)useSnapshotOverlay;
- (BOOL)isBeingDestroyed;
- (void)setContextMenuProvider:(id)fp8;
- (id)contextMenuProvider;
- (void)setNativeProvider:(id)fp8;
- (id)nativeProvider;
- (id)delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)injectWebView:(id)fp8 snapshotManager:(id)fp12 popupHandler:(struct BlockedPopupHandler *)fp16;
- (void)injectSnapshotManager:(id)fp8;
- (void)setSuppressDialogs:(BOOL)fp8;
- (void)internalSuppressDialogs:(BOOL)fp8;
- (void)setOverlayPreviewMode:(BOOL)fp8;
- (void)removeSnapshotOverlay;
- (void)addSnapshotOverlay;
- (BOOL)userIsInteracting;
- (id)touchTrackingRecognizer;
- (void)touched:(BOOL)fp8;
- (struct BlockedPopupHandler *)popupHandler;
- (void)openPopupFromDictionary:(id)fp8;
- (void)setKeyboardOverlayHeight:(float)fp8;
- (void)disableFindInPage;
- (void)findPreviousStringInPage;
- (void)findNextStringInPage;
- (BOOL)processFindInPageResult:(id)fp8;
- (BOOL)pumpFindStringInPage;
- (BOOL)findStringInPage:(id)fp8;
- (void)updateFindInPageIndex:(struct FindInPageEntry)fp8;
- (struct FindInPageEntry)findInPageEntryForJson:(id)fp8;
- (struct FindInPageEntry)entryForListValue:(struct ListValue *)fp8;
- (void)initFindInPage;
- (BOOL)canFindInPage;
- (BOOL)isFindInPageJSPresent;
- (id)findInPageModel;
- (BOOL)gestureRecognizer:(id)fp8 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)fp12;
- (void)actionSheet:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)generateMissingDocumentLifecycleEvents;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)notifyPasswordControllerForWebView:(id)fp8 willStartLoadingRequest:(id)fp12 navigationType:(int)fp16;
- (void)generateErrorPageForUnsupportedURL:(id)fp8;
- (void)showResubmitDataActionSheet:(id)fp8;
- (void)removeContinuousCheckTimer;
- (void)setContinuousCheckTimer:(double)fp8;
- (void)periodicJSCheck;
- (void)performJSChecks;
- (void)checkForTitleChange;
- (void)checkForURLChange;
- (void)pageChanged;
- (BOOL)isDefaultPage;
- (void)respondToMessageQueue:(const struct basic_string<char, std::char_traits<char>, std::allocator<char>> *)fp8 userIsInteracting:(BOOL)fp12;
- (void)respondToJSInvoke:(id)fp8;
- (void)documentLoaded;
- (id)stringByEvaluatingUserJavaScriptFromString:(id)fp8;
- (id)stringByEvaluatingJavaScriptFromString:(id)fp8;
- (struct Value *)jsonDataByEvaluatingJavaScriptFromString:(id)fp8;
- (void)loadCompleteWithSuccess:(BOOL)fp8;
- (BOOL)isLoaded;
- (void)stopLoading;
- (void)abortLoad;
- (void)reload;
- (void)loadHTML:(id)fp8;
- (void)loadCurrentURL;
- (void)loadCurrentURLInNativeView;
- (void)loadErrorInNativeView:(id)fp8;
- (void)loadNativeViewWithSuccess:(BOOL)fp8;
- (void)loadCurrentURLInWebView;
- (void)finishPushStateNavigationToURL:(id)fp8 withStateObject:(id)fp12;
- (void)registerLoadRequest:(id)fp8 referrer:(id)fp12 transition:(int)fp16;
- (id)view;
- (id)createWebView;
- (void)documentPresent;
- (void)injectChromeObject;
- (id)webViewDocumentType;
- (BOOL)isChromeJSPresent;
- (void)loadJavaScriptToInject;
- (BOOL)isUserScalable;
- (void)setPageState:(id)fp8;
- (id)pageState;
- (id)currentReferrer;
- (id)currentURL;
- (id)currentURLWithTrustLevel:(int *)fp8;
- (void)presentSpoofingErrorWithURL:(id)fp8;
- (struct CGPoint)scrollPosition;
- (struct CGSize)windowSize;
- (void)retrieveSnapshot:(id)fp(null);
- (id)updateSnapshot;
- (id)generateSnapshotOrDefault;
- (id)generateSnapshotWithOverlay:(BOOL)fp8;
- (BOOL)shouldCacheSnapshot;
- (void)showContextMenu:(id)fp8;
- (BOOL)gestureRecognizerShouldBegin:(id)fp8;
- (id)getContextDictionary:(id)fp8 title:(id *)fp12;
- (id)passwordController;
- (void)close;
- (BOOL)isViewAlive;
- (void)handleLowMemory;
- (void)resumeWebUsage;
- (void)suspendWebUsage;
- (BOOL)runUnloadListenerBeforeClosing;
- (void)dealloc;
- (void)removeWebView;
- (void)setDelegate:(id)fp8;
- (void)setInterstitial:(id)fp8;
- (id)interstitial;
- (id)initWithProfile:(struct Profile *)fp8;

@end

