/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "PrerenderDelegate-Protocol.h"
#import "TitleChangedDelegate-Protocol.h"

@protocol WebDelegate <TitleChangedDelegate, PrerenderDelegate>
- (void)presentSpoofingErrorWithURL:(id)fp8;
- (BOOL)useDesktopUserAgent;
- (void)replaceStateWithPageURL:(id)fp8 stateObject:(id)fp12;
- (void)pushStateWithPageURL:(id)fp8 stateObject:(id)fp12;
- (void)goDelta:(int)fp8;
- (void)goForward;
- (void)goBack;
- (float)infoBarOverlayYOffset;
- (id)infoBarOverlayView;
- (struct InfoBarTabHelper *)infoBarTabHelper;
- (void)webPageWrite:(id)fp8 html:(id)fp12;
- (void)webPageStop:(id)fp8;
- (void)webPageOrderedClose:(id)fp8;
- (void)webPageOrderedClose;
- (void)webPageOrderedOpen:(id)fp8 referrer:(id)fp12 windowName:(id)fp16 inBackground:(BOOL)fp20;
- (id)currentHttpHeaders;
- (id)currentPOSTData;
- (id)currentSessionID;
- (id)currentState;
- (id)currentURLReferrer;
- (int)currentTransition;
- (id)currentURL;
@end

