/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "ToolbarController.h"

#import "LocationBarDelegate-Protocol.h"
#import "OmniboxPopupPositioner-Protocol.h"
#import "VoiceSearchControllerDelegate-Protocol.h"

@class OmniboxTextFieldIOS, UIButton, UIView;

@interface WebToolbarController : ToolbarController <LocationBarDelegate, VoiceSearchControllerDelegate, OmniboxPopupPositioner>
{
    UIView *webToolbar_;
    UIButton *backButton_;
    UIButton *forwardButton_;
    UIButton *reloadButton_;
    UIButton *stopButton_;
    UIButton *starButton_;
    UIButton *voiceSearchButton_;
    OmniboxTextFieldIOS *omniBox_;
    UIButton *cancelButton_;
    struct scoped_nsobject<UIView> keyboardAccessoryView_;
    struct scoped_nsobject<DeterminateProgressBar> determinateProgressBar_;
    struct scoped_ptr<ui::Animation> progressBarAnimation_;
    struct scoped_ptr<ProgressBarAnimationDelegate> progressBarAnimationDelegate_;
    id <UrlLoader><WebToolbarDelegate> delegate_;
    struct scoped_ptr<LocationBarViewIOS> locationBar_;
    BOOL initialLayoutComplete_;
    BOOL incognito_;
    BOOL unitTesting_;
    struct scoped_nsobject<UIImage> snapshot_;
    unsigned int snapshotHash_;
    struct ObjCPropertyReleaser propertyReleaser_WebToolbarController_;
}

- (void)setCancelButton:(id)fp8;
- (void)setOmniBox:(id)fp8;
- (id)omniBox;
- (void)setVoiceSearchButton:(id)fp8;
- (id)voiceSearchButton;
- (void)setStarButton:(id)fp8;
- (id)starButton;
- (void)setStopButton:(id)fp8;
- (id)stopButton;
- (void)setReloadButton:(id)fp8;
- (id)reloadButton;
- (void)setForwardButton:(id)fp8;
- (id)forwardButton;
- (void)setBackButton:(id)fp8;
- (id)backButton;
- (void)setWebToolbar:(id)fp8;
- (id)webToolbar;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)recordUserMetrics:(id)fp8;
- (struct CGRect)bookmarkBubblePoint;
- (void)stackButtonTouchDown:(id)fp8;
- (void)receiveVoiceSearchResult:(const struct SpeechRecognitionResult *)fp8;
- (void)showStopButton;
- (void)showReloadButton;
- (void)hideProgressBarAndTakeSnapshot;
- (void)stopProgressBar;
- (void)startProgressBar;
- (void)selectedTabChanged;
- (void)currentPageLoadStarted;
- (struct CGRect)popupFrame:(float)fp8;
- (id)popupParentView;
- (void)locationBarBeganEdit;
- (void)locationBarHasResignedFirstResponder;
- (void)locationBarHasBecomeFirstResponder;
- (void)userHasNavigatedAwayFromPage:(id)fp8;
- (void)pressKey:(id)fp8;
- (id)updateTextForDotCom:(id)fp8;
- (void)loadGURLFromLocationBar:(const struct GURL *)fp8 referrer:(const struct GURL *)fp12 transition:(int)fp16;
- (void)standardButtonPressed;
- (void)setControlsHidden:(_Bool)fp8;
- (void)showPrerenderingAnimation;
- (void)updateSnapshotWithWidth:(float)fp8 forced:(BOOL)fp12;
- (unsigned int)snapshotHashWithWidth:(float)fp8;
- (void)updateToolbarState:(const struct ToolbarState *)fp8;
- (void)setForwardButtonEnabled:(BOOL)fp8;
- (void)setBackButtonEnabled:(BOOL)fp8;
- (void)layoutOmnibox;
- (void)focusOmniBox;
- (struct LocationBarViewIOS *)locationBar;
- (void)dealloc;
- (id)initWithProfile:(struct Profile *)fp8 prerenderProvider:(id)fp12;
- (id)keyboardAccessoryView;
- (id)keyboardButtonWithTitle:(id)fp8 frame:(struct CGRect)fp12;
- (id)snapshotWithWidth:(float)fp8;
- (id)cancelButton;
- (void)cancelOmniboxEdit;
- (void)cancelButtonPressed:(id)fp8;

@end

